### ISSUE TITLE
ValueError: Invalid fragment string

### ISSUE THREAD

**Issue by vstoykov** [pypa/pipenv#1121]
I'm trying to convert existing `requirements.txt` file with:
```
pipenv install -r requirements.txt
```

##### Describe your environment

1. Fedora 26
1. Python version: 3
1. Pipenv version: version 8.3.2

##### Expected result

Everything to be installed without errors

##### Actual result

It raises an error:
```
ValueError: Invalid fragment string egg=django-user-clipboard==0.6.1
```

##### Steps to replicate

You need to have requirements.txt file which will have URL entries pointing to package archive file but ending with `#egg=<package-name>==<package.version>`

For example:
```
https://github.com/IndustriaTech/django-user-clipboard/archive/0.6.1.zip#egg=django-user-clipboard==0.6.1
```

If you try to convert this `requirements.txt` file to `Pipfile` with `pipenv install -r requirements.txt` it will fail.

**Comment by vstoykov** [comment]
I upgraded to 9.0.1 and the bug is still there.

**Comment by nateprewitt** [comment]
Hey @vstoykov, thanks for reaching out. Could I ask why you're using this notation and why you expect it to work? This isn't documented as working for Pip in the official documentation as far as I can tell, and conceptually doesn't really make sense. The examples using the fragment in the documentation for [`pip install`](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support) show that a package name with a version should be represented as <project_name>-<version>. There's also the semantics of key value pairs represented as `k=v` and this notation breaks parsing for that.

The fact that this works is because pip is currently ignoring the egg fragment since it's installing straight from the source repository. I don't have an issue patching this so we exit in a nicer fashion, but I'm not convinced this is something we should be supporting. If I'm missing something though, please let us know and I'm happy to change my mind if we have a compelling reason.

**Comment by techalchemy** [comment]
@nateprewitt before I wrote the PR I did verify that the syntax is valid in the docs and also that it works by default with `pip install` -- I checked how the pip internals handle parsing these inputs which is how I came to the changes I included in my PR.  While the syntax is unusual, the changes in my PR bring us more in line with how pip handles inputs from the user and actually will make us more robust ultimately in terms of parsing package names and such.

I feel the approach at least from an internal perspective is important, since it takes all URI inputs and parses them to `pip.index.Link` objects before handing them off to the requirements parser.  Really I just feel this is a good idea, somewhat independently of this issue.

From [working out the name and version](https://pip.pypa.io/en/stable/reference/pip_install/#working-out-the-name-and-version):

> Any URL may use the `#egg=name` syntax (see [VCS Support](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support)) to explicitly state the project name.

**Comment by nateprewitt** [comment]
@techalchemy, can you please link the documentation section and source code you're referring to?

**Comment by techalchemy** [comment]
To clarify there is no documentation I am aware of that would allow you to put version specifiers on urls

**Comment by vstoykov** [comment]
I'm not sure where I saw this for the first  time (It was years ago).

This way pip does not try to download it if the specified version is
already installed. This will speed up the routine `pip install -r
requirements.txt` on deploy when there are no changes in requirements.

This is similar to dependancy_links where you say from where to download
specific package instead of looking in the package index.

I'm using this approach for packages which I still think are not ready for
PyPi (for wider usage), but there are some versions, and not all projects
using given package are ready for master.

If in Pipfile you can define the same thing:
1. Package and version;
2. From where to download the package to be downloaded if it's not already
installed without searching in package index;

That would be great.

На 22.12.2017 г. 9:57 пр.об. "Dan Ryan" <notifications@github.com> написа:

**Comment by techalchemy** [comment]
@vstoykov but you’re just making up a number at that point. Internally, pip takes the number and (unless the path you supply is a `file://` URI to a wheel) it just says ok, you told me it’s this version... cool whatever, still gonna install the thing you said. Ultimately it will get actual version info from the file. 

Anyway we are having two conversations here. One relates to how we should build out our internals for handling requirements parsing, and the other relates to whether your syntax is valid/effective. I’d say that adding a specified to your URL probably isn’t doing anything at best, so the real question is just whether we adopt pip’s behavior of parsing links.

**Comment by jpz** [comment]
I’ve encountered this also - here is an example requirements file that pipenv does not like - https://github.com/home-assistant/home-assistant/blob/dev/requirements_all.txt
