### ISSUE TITLE
[Feature request] update packages _only_ if pipefile.lock is missing or out of date

### ISSUE THREAD

**Issue by BeyondEvil** [pypa/pipenv#1138]
We distribute a script which in turn uses pipenv to run some python code. We do this to be able to have our script be portable.

What we are looking for is a way to check/verify that the machine the script is running on has the latest version of the pipfile.lock file.

Workaround is to always run `pipenv install` which works the way we want IF the pipefile.lock is missing or invalid. But it doesn't when everything is OK. Meaning, what happens then is that it uninstalls/removes everything and reinstalls. The option, if present, would simply do nothing at this point.

I hope that makes sense?

**Comment by techalchemy** [comment]
I can think of three options currently and hopefully one of them can help, but maybe others can come up with more. 

- You can check the return code of `pipenv install —deploy` which will fail to install in the first place if the lockfile is out of date
- You can check the output of `pipenv update —dry-run` and see if it is suggesting anything, you can check for `‘All good!’` in the output
- You can add a version tag in the system metadata section if you’re distributing this yourself, but this may not be very reliable because dependencies may need to re-resolve on other systems which will wipe any changes you make

**Comment by BeyondEvil** [comment]
Thanks @techalchemy for your suggestions.

I'll checkout `-deploy`

As for `--dry-run`, I thought of that too, but there seems to be an issue with it (see my comment here: https://github.com/kennethreitz/pipenv/issues/810#issuecomment-348127544).
Apart from that issue, I'm not sure that would pick up any additions/removals to the pipfile, only new/change dependencies - right?

As for the third suggestion, like you said yourself - won't be reliable since we distribute this to different systems.

**Comment by techalchemy** [comment]
@BeyondEvil we had a discussion about something like this in #1080 which involved a check for whether the lockfile /pipfile were in sync with the venv, which isn’t currently implemented but could be

A rough implementation would just be to do `pipenv run pip freeze`and use a json parser on the lockfile to compare.  

As for picking up changes to the Pipfile, that’s what `—deploy` does

**Comment by BeyondEvil** [comment]
Thanks @techalchemy I checked out the two issues you mentioned and then I coded something in #1168 

Let me know what you guys think.
