### ISSUE TITLE
Options to improve Python runtime autodiscovery on Windows

### ISSUE THREAD

**Issue by ncoghlan** [pypa/pipenv#1150]
Pipenv currently has two Python runtime discovery and/or installation strategies:

1. Search `PATH` (in `pipenv.cli.find_a_system_python`), adding any `pyenv` environments to the end before it does so
2. Install it with `pyenv` (in `pipenv.cli.ensure_python`)

This misses a few potential possibilities for improvement on Windows:

1. Discovery based on the Windows launcher configuration file (https://docs.python.org/3/using/windows.html#customization)
2. Discovery based on the Windows registry (https://github.com/zooba/pep514tools#usage)
3. Supporting `conda` based automatic Python installation in addition to `pyenv` installation
4. Supporting @uranusjr's https://github.com/uranusjr/pythonup-windows (and its macOS counterpart)

Actually doing this would probably requiring refactoring the autodiscovery code though, such that the discovery & installation strategy used by `ensure_python` can be chosen at import time based on the platform.

**Comment by uranusjr** [comment]
#841 :(

**Comment by uranusjr** [comment]
The launcher also looks for some environment variables, so that should probably be considered as well. I’m pretty interested in working on this feature, but probably can’t put much real effort until the end of the year.

**Comment by ncoghlan** [comment]
@uranusjr Cool! I'm actually thinking it may make more sense to start by refactoring the existing "Python finding" code out of `pipenv.cli` and into a separate `pipenv.pythonfinder` helper module.

The reason I suggest that is because the way the current `pyenv` integration works is as follows:

1. There's an `activate_pyenv` step that adds all installed pyenv Python's to `PATH` in the current process
2. There's the usual `find_a_system_python` step to actually locate an installed Python
3. There's then a fallback to ask `pyenv` to *install* the requested Python, if it isn't found otherwise

That gives us 3 operations to abstract away:

* building an inventory of "available Python runtimes" (current implementation: add `pyenv` executables to PATH)
* searching the Python runtime inventory for a requested version (current implementation: scan PATH for suitably named files)
* requesting installation of a particular version if nothing appropriate is found (current implementation: run `pyenv` in a subprocess)

So I'm picturing an API where the usage looks something like this in `cli.ensure_python`:

    # Existing code to figure out `python`
    path_to_python = pipenv.pythonfinder.get_runtime_path(python)
    if path_to_python is None and PIPENV_SHOULD_AUTO_INSTALL:
        path_to_python = pipenv.pythonfinder.install_runtime(python, confirm_callback=confirm, abort_callback=abort)

Only the latter two identified operations (finding a runtime and installing a runtime) would be visible outside the `pipenv.pythonfinder` module. Actually building the inventory of available runtimes would be an internal implementation detail of the `pipenv.pythonfinder` module, and happen implicitly when the CLI searches for a Python installation.

(That's glossing over a lot of details, but gives a general idea of what I'm thinking)

(cc @erinxocon)

**Comment by uranusjr** [comment]
@ncoghlan Wow, I’ve been thinking about the same refactoring as well, and even came up with the same submodule name 😅 Glad to know I was on the right track.

The problem I have with the current implementation it that, it might not be able to integrate PEP 514. If I read the PEP correctly, it allows a distribution to use an arbitrary executable name (with `InstallPath\ExecutablePath`). For `PythonCore`  (i.e. installers from python.org) it is always `InstallPath` + `\python.exe`, but that might not be the case for other distributions. I’m not aware of any distributions/implementations using a different executable name (Anaconda also uses `python.exe`, and pypy doesn’t implement PEP 514 at all), but it might be better to be more future-proof.

My thought is to implement multiple finders:

* `pipenv.pythonfinders.GlobalPythonFinder`: Look for `python`, `pythonX`, and `pythonX.Y` in `PATH`, and call it to check whether it has the right version.
* `pipenv.pythonfinders.PyEnvFinder`: Look for a matching version from pyenv.
* `pipenv.pythonfinders.PEP514Finder`: Look for a matching version in the registry.

When the user calls `get_runtime_path()`, it detects what finder(s) to use. If pyenv is installed (i.e. the right environs are set), use `PyEnvFinder` and `GlobalPythonFinder`; if on Windows, use `PEP514Finder` and `GlobalPythonFinder`, etc. This way we don’t need to rely on the `PATH` environ to find the right Python, and I think is the right level of abstraction.

P.S. In regard of `install_runtime`, I’m currently working on a Python version-management tool for Windows ([uranusjr/snafu](https://github.com/uranusjr/snafu)). The idea is to abstract away the download, install, configure part of installing Python on Windows, so the user can manage multiple Python installations with minimal fuss. It plays a similar role as pyenv, but instead of building just use the official binaries.  This could be useful if Pipenv wants to provide auto installation on Windows.

**Comment by ncoghlan** [comment]
@uranusjr Aye, that matches what I was thinking as well. The main case where interpreter names that don't follow the "python[X[.Y]]" convention comes up is when using an alternative implementation like PyPy.

I also like the idea of having an auto-updater for the python.org binaries as the baseline option on Windows - then `conda` support can be handled as a UX enhancement for conda users, rather than as a baseline requirement for automated runtime installation on Windows.

**Comment by kaste** [comment]
Hi 👋! In the last version of #1259 there was actually no PEP514Finder as far as I could read. That approach didn't work out at all? The meat of #1259 was just the refactoring?

**Comment by uranusjr** [comment]
@kaste That approach involves both a refactoring and PEP 514 support, but Kenneth wasn’t comfortable with the refactoring part. But my PEP 541 implementation doesn’t work well (I don’t think) without the refactoring, so the path is kind of dead now. I’m actually working on [a tool](https://github.com/uranusjr/pythonup-windows) not directly related to Pipenv, but as a bonus effect can work with it without PEP 514 (because it provides compatible commands). Grab a build ([64-bit](https://ci.appveyor.com/project/uranusjr/pythonup-windows/build/job/vqr17yohin6f3mtg), [32-bit](https://ci.appveyor.com/project/uranusjr/pythonup-windows/build/job/47jw8qi12776r9gj)) if you feel adventurous.

**Comment by kaste** [comment]
Kenneth can be a bit tricky sometimes, but a PR just with a refactoring without the meat I would have rejected as well.

Still, Windows is not a first citizen currently. It didn't work for me (without manual adding stuff to PATH). It is not considered a good practice to put 5 versions of python on PATH. And, AFAIK, the windows installer by default does not add to the PATH.

**Comment by kaste** [comment]
Oh, I see that @ncoghlan was the champion here actually, so honestly, you're PR @uranusjr was super-dope 👌 👏  , the refactoring was clean and readable. (Actually, I waited for the merge and wanted to use that in a different project.) And, I would feel really fucked up by that rejection. 🙌

**Comment by uranusjr** [comment]
@kaste Your workflow seems a lot like mine (not adding things to PATH, need to constantly switch between Python versions, etc.), so one final plug if I may… That pythonup-windows tool I mentioned above will likely be a very good fit 😉

**Comment by ncoghlan** [comment]
I've updated the initial comment to mention https://github.com/uranusjr/pythonup-windows, as that seems like the most promising path forward in the near term. I do think it will be worthwhile supporting conda, and maybe some of the other vendor provided Python binaries, but it would be nice to be able to do that through some kind of generic discovery mechanism that vendors can opt in to (like PEP 514 on Windows), rather than having `pipenv` be explicitly aware of all the various options.

**Comment by ncoghlan** [comment]
Reopening this, as I didn't realise it had been closed, and without adequate Python runtime autodiscovery, pipenv's Windows support is far from being in the same class as its support for Windows and Mac OS X.

**Comment by uranusjr** [comment]
A summary of the current situation:

* PATH-based discovery and pyenv discovery is unchanged.
* A `py.exe`-based discovery has been implemented on Windows. As long as `py.exe` is present in PATH, `--python=X.Y` will consult it to discover Python installations. This has some minor restrictions (not able to discover WOW6432 installations, for example).
* A standalone library, [pythonfinder](https://github.com/sarugaku/pythonfinder), has been developed aiming to replace the current strategy. The integration is in progress, but is far from being finished. (I feel maybe we should scale the integration effort back a little, and use it only for *discovery* for now).
* pyenv is still the only option available for auto-installation. I did a minor rewrite in #2572, but there’s no change in functionality.

**Comment by ncoghlan** [comment]
Thanks for the status update @uranusjr!

Given that, perhaps it would make sense to close this issue again, and replace it with two new ones:

- using pythonfinder for runtime discovery (already in progress)
- supporting more options for runtime auto-installation (if that ends up being a pythonfinder feature, cool, but having the pipenv issue open makes it clear that the absence is due to it being a significant challenge to get auto-installation to work consistently across different Python runtime managers, rather than a permanent restriction to only supporting pyenv)

**Comment by techalchemy** [comment]
I believe this should be fixed since we brought in `pythonfinder` but do let me know if it is still an issue

**Comment by uranusjr** [comment]
I wonder if version _installation_ can be supported like pyenv. It doesn’t need to be first-class, but maybe a plugin interface to hook into so people can create e.g. `pipenv-anaconda` to get a similar experience.

**Comment by techalchemy** [comment]
or perhaps `pipenv-pythonup`? :)

**Comment by uranusjr** [comment]
Er yeah I guess, if someone’s interested in developing that (I’m not, I don’t need Pipenv to help me install my Pythons).
