### ISSUE TITLE
Feature Request Docs Improvements

### ISSUE THREAD

**Issue by stevepiercy** [pypa/pipenv#1156]
I'd like to see the following changes to improve the usability of the documentation:

* Add a search box site wide.
* Fix search results to use the proper URL. For example: https://docs.pipenv.org/search.html?q=virtualenv shows the resulting URL for the first link as http://docs.pipenv.org/en/latest/index.html?highlight=virtualenv but it should be https://docs.pipenv.org/index.html?highlight=virtualenv
* Provide some navigational context where users know where they are in the docs through either a left sidebar, breadcrumbs, Next and Previous links, or both.
* Use a theme that is consistent with the PyPA which includes all these features out of the box.

Thank you for your consideration.

**Comment by MatMoore** [comment]
This looks related to https://github.com/kennethreitz/pipenv/issues/982.

@erinxocon It seems like for the short term we should remove this search page as well ☹️

If you run the docs locally, it works fine, because it uses the Sphinx built in search. But readthedocs have their own search functionality which seems to override it. Their API always returns links containing `/en/latest` which as far as I can tell is correct, because readthedocs projects always have some version associated with them. I'm assuming `docs.pipenv.org` is deliberately stripping these out of the URLs?
