### ISSUE TITLE
`pipenv lock -r` is not deterministic

### ISSUE THREAD

**Issue by konstin** [pypa/pipenv#1214]
##### Describe your environment

Ubuntu 17.04, Python 3.5.3, pipenv 9.0.1

##### Expected result

`pipenv lock -r` returns the exact same output when given the same Pipfile and Pipfile.lock.

##### Actual result

`pipenv lock -r` randomly  reorders lines on each run. This becomes a problem when combined with `pipenv lock -r > requirements.txt` and version control, as it chances `requirements.txt` even if there is no actual change. 

##### Steps to replicate

Create a project with Pipfile and Pipfile.lock ([mine](https://github.com/meine-stadt-transparent/meine-stadt-transparent) for reference). Run `pipenv lock -r`.

##### Workaound

A possible workaround is `pipenv lock -r | sort`.

**Comment by konstin** [comment]
@kennethreitz Why was this closed?

**Comment by kennethreitz** [comment]
send a pull request if you want to fix it!

**Comment by beregon87** [comment]
While not a real solution to the problem, why not generate `requirements.txt` on the fly when you need it? In fact, I would argue that you shouldn't commit it since at best it just duplicates whatever is in Pipfile and at worst they would differ because someone forgot to do `pipenv lock -r > requirements.txt`.
