### ISSUE TITLE
--system does not use --python

### ISSUE THREAD

**Issue by grantstephens** [pypa/pipenv#1223]
So I may have the usage wrong, but essentially I want to use pipenv in a docker container, but install the packages using `pypy3` in this case, so I am trying to do:
`pipenv install --system --python pypy3`

This however gives the error that `/bin/python` cannot be found, which makes me think that it is ignoring the `--python` when used with the `--python` argument. 

If this is expected then how do I install the packages in a docker container using another version of python like `pypy3`?

##### Describe your environment

1. OS Type: Ubuntu 17.04
1. Python version: pypy3
1. Pipenv version: 9.0.1

**Comment by techalchemy** [comment]
@grantstephens thanks for the report.  `--system` and `--python` are kind of mutually exclusive if you will.  If you pass `--system`, pipenv always uses `sys.executable` which is whatever version of python pipenv is running in.  Passing `--python` implies to pipenv that you want it to make a virtualenv for you.  That said I am really not sure how things will work out with pypy3, but combining these two flags won't work.  I suspect you may want to try this out by having pypy3 as your virtualenv python by simply removing the `--system` flag and using `pipenv run` to invoke python code in that context.

I'll leave this open since I'd like to know if this works :)

**Comment by grantstephens** [comment]
Ah, I figured something like that was going on and it makes sense- thanks for explaining it. I can get it to run perfectly locally with `pypy3` or whichever interpreter I want (Just depends on how the `virtualenv` is set up), the problem is in the docker container. Now I could run it in a `virtualenv` in the container (as you suggested, which works), but that kinda defeats the point of having a small lightweight container. 

I also considered simlinking over `/bin/python`, but that is probably not a good idea.

Essentially it comes down to wanting to not create a `virtualenv` and not use `/bin/python` but specify and executable that should be used. 

It seems that `pipenv` still goes for `/bin/python` even when it was installed using a `pip` and interpreter that are not that, i.e. `pip install pipenv` installs `pipenv` using `pypy3` for me, but it still tries to use `/bin/python` when doing `pipenv install`

**Comment by techalchemy** [comment]
@grantstephens I dont know too much about pypy but I suspect it's because it is looking for `python` or whatever, but not finding it.  Do you know what the value of `sys.executable` is in a pypy interpreter?

**Comment by grantstephens** [comment]
Just checked- it is the pypy executable.  I'll go and double check that this is also the case for `pypy` in the docker image, but something was looking for python in `/bin/python`

Just to confirm- `pipenv` with `--system` should use the executable specified in `sys.executable`?

**Comment by techalchemy** [comment]
yes, unless `--system` isn't falling through to the `which()` call in question (see #1002)

**Comment by techalchemy** [comment]
Closing for now as I don't think pypy support is on the roadmap but maybe sometime in the future :)
