### ISSUE TITLE
Fails to recognize .env on Windows 10

### ISSUE THREAD

**Issue by mattharrison** [pypa/pipenv#1271]
Be sure to check the existing issues, both open and closed.

I want pipenv to recognize the .env in my directory. Rather when I type ``pipenv shell``, it goes off and creates a new env.

##### Describe your environment

1. Windows 10 (Surface Pro)
1. Python version: python 3.6.4
1. Pipenv version: 9.0.1

##### Expected result
Uses existing environment (.env)

##### Actual result

Creates a new environment, in ``C:\User\matt\.virtualenvs\labs-FF_PAFzP``

##### Steps to replicate

1. Install Python
1. Install pipenv in user installation
1. Create a virtual environment in the current directory named ``.env``
1. Run ``pipenv shell``

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by mattharrison** [comment]
NVM, I read .env, but skimmed after that...

**Comment by nateprewitt** [comment]
Hey @mattharrison, could you clarify a couple things really quickly. When you say `.env`, do you mean the environment variable initialization file, or you are creating a virtualenv in a directory called `.venv`?

If it’s the latter, pipenv actually supports this currently. You can set the environment variable `PIPENV_VENV_IN_PROJECT`, and pipenv will choose to use the local `.venv` directory. Note the name is .venv instead of .env, to avoid conflicts with the file we also support.

If you’re talking about the initialization file, I’m not sure I’m following. Could you explain a bit more in that case?

**Comment by mattharrison** [comment]
Hi @nateprewitt thanks for your response. I meant creating a virtual environment named (.env or .venv). I figured it out. For any others with (windows) issues:

    C:\ python -m venv .venv
    C:\ set PIPENV_VENV_IN_PROJECT=1
    C:\ pipenv shell
    C:\ pipenv --py

The final command should show that you are using the virtualenv you created.
