### ISSUE TITLE
/tmp fills up with pipenv-*-requirement.txt files

### ISSUE THREAD

**Issue by SethMichaelLarson** [pypa/pipenv#1273]
Temporary directory fills up with many temporary requirements.txt files.
Using Pipenv frequently results in hundreds of files in `/tmp`.

##### Describe your environment

1. Ubuntu 17.10
1. Python version: `Python 3.6.2`
1. Pipenv version: `pipenv, version 8.2.6`

##### Expected result

Pipenv cleans up these files after completing successfully.

##### Actual result

Pipenv leaves the temporary files.

##### Steps to replicate

Run these steps in an empty directory

```bash
$ rm -rf /tmp/pipenv-*
$ ls -Al /tmp | grep pipenv | wc -l # 0
$ pipenv install pytest
$ ls -Al /tmp | grep pipenv | wc -l # 2
```

**Comment by nateprewitt** [comment]
Yep, this is a known issue and we keep closing the tickets around it. I’d like to use this as the tracking ticket going forward. The issue here is we’re using TemporaryFiles mkstemp instead of using the object as a context.

There may be other areas that need cleanup around this but those are the cases generating the largest volume. Anyone who would like to look into fixing this is welcome. We just need to make sure the solution is cross platform compatible.

Thanks @SethMichaelLarson for getting this issue logged.

**Comment by kennethreitz** [comment]
fixed
