### ISSUE TITLE
Selectively skip package from Pipfile

### ISSUE THREAD

**Issue by lk-geimfari** [pypa/pipenv#1334]
How about the feature for skipping some packages selectively, I mean something like this:

```bash
~ pipenv install --skip "mypy"
```

Why?

Some packages not incompatible with some implementations of Python (`mypy` does not work with `PyPy` for example) and it would be awesome to have feature for skipping such packages on installing.

For example on building on CI:

```
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy3" ]]; then pipenv install --dev --skip "mypy"; fi
```

**Comment by uranusjr** [comment]
I feel [PEP 508]-style markers is the better approach to this kind of problems. Instead of just `mypy = "*"`, write this in the Pipfile:

```toml
mypy = { version = "*", platform_python_implementation = "=='CPython'" }
```

The syntax should be pretty straightforward, and there are quite some variants available. See [PEP 508] for a list of available markers, and examples in [Pipfile]’s README for some examples.

[PEP 508]: https://www.python.org/dev/peps/pep-0508/
[Pipfile]: https://github.com/pypa/pipfile

**Comment by lk-geimfari** [comment]
@uranusjr Sounds good. I'll try it. Thank you!
