### ISSUE TITLE
Running pipenv install to generate Pipfile.lock changes/normalizes package name

### ISSUE THREAD

**Issue by stephendonner** [pypa/pipenv#1386]
When running ```pipenv install``` the querystringsafe_base64 package gets renamed/normalized to querystringsafe-base64, in the resulting, generated Pipfile.lock file

It can be seen in https://github.com/mozilla/stubattribution-tests/commit/c24d26ed6861dc0c7f382e1968a19bffb553ec95

##### Describe your environment

1. macOS High Sierra (10.13.4 Beta (17E139j))
1. Python version: Python 2.7.11 (locally)
1. Pipenv version: pipenv, version 8.3.2

##### Expected result

While I'm not sure, I'd expect that ```querystringsafe_base64``` would either be left as-is, or renamed, consistently, to ```querystringsafe-base64```

##### Actual result

Pipfile.lock has ```querystringsafe-base64```, whereas the Pipfile itself has ```querystringsafe_base64```

##### Steps to replicate

* pipenv install with https://github.com/mozilla/stubattribution-tests/blob/845824793062bc7a2b33faa6ccc2e8a796775932/Pipfile in place
* Look at the package-dependency name in both the resulting Pipfile.lock and the original Pipfile, for **querystringsafe_base64**

**Comment by stephendonner** [comment]
[verbose-log.txt](https://github.com/pypa/pipenv/files/1687379/verbose-log.txt)

**Comment by uranusjr** [comment]
PyPI performs this normalisation to ensure package names are of a certain format, as specified in [PEP 503](https://www.python.org/dev/peps/pep-0503/). `querystringsafe_base64` is not a valid package name, and is normalised by PyPI to `querystringsafe-base64`, which is the “real” package name PyPI (and Python packaging tools) uses to recognise the package. If you look into the `site-packages` directory you installed the package in, you would find a `querystringsafe-base64-<version>.egg-info` which reflects this.

Since the lock file is generated from the actual installation, it contains the normalised, actual identifier of the package on PyPI. It is unnecessary to convert the name back to what you entered because there is not inherent advantage (aside from user preference), and would require an extra conversion when you use the lockfile later. The lockfile is not intended to be manually inspected by the user anyway.

Also note that if you use the auto-append feature (`pipenv install <package>`) instead of manually adding the package name into Pipfile, all your package names in Pipfile would also be converted to the normalised form as the lock file.

**Comment by nateprewitt** [comment]
Hey @stephendonner, thanks for reporting this. As @uranusjr said, Pipfile.lock isn't intended for use or consumption by a user. The normalized name convention specified in PEP 503 makes - and _ interchangeable.

That said, we had a regression around our normalization that was only recently identified, and hasn't been triaged yet. We originally used the casing and `-`/`_` preference of the package owner in the Pipfile and Pipfile.lock, and only had the normalized format for internal use. Somewhere a long the line, we short circuited "recasing" the names before writing back to the file, and they've been stuck in the normalized format since.

We have the initial diagnosis tracked in #1314 which is a slightly different manifestation of the same underlying issue.

**Comment by stephendonner** [comment]
Thanks @uranusjr and @nateprewitt - I should mention that this came about because the @pyup-bot issued two separate PRs for our repo, and they thought it might be due to this internal "discrepancy.":

* one for our Pipfile: https://github.com/mozilla/stubattribution-tests/pull/109
* one for the Pipfile.lock: https://github.com/mozilla/stubattribution-tests/pull/108

(Just context for filing, which I should've lead with, sorry!)

**Comment by kennethreitz** [comment]
Closing as a non-issue for the moment.
