### ISSUE TITLE
Switch to the PyPA docs theme?

### ISSUE THREAD

**Issue by ncoghlan** [pypa/pipenv#1456]
In https://github.com/pypa/python-packaging-user-guide/issues/437, @stevepiercy pointed out that the current visual styling of the `pipenv` docs reflect's Kenneth's personal docs style, moreso than the common PyPA style we've been adopting for `pip`, the Python packaging user guide, etc.

If folks are OK with the idea of migrating to the PyPA theme, then I'd be happy to put together a PR for that.

**Comment by kennethreitz** [comment]
@ncoghlan I'm open to it, but would want to approve before merging.

**Comment by kennethreitz** [comment]
We may want to remain a special snowflake.

**Comment by kennethreitz** [comment]
Just because this is a PyPA project now, doesn't mean it's not a Kenneth Reitz project still. I think switching the theme would lose a lot of the branding, and take away from the feel of the project in general.

So, I'm actually going to -1 this, for now. I don't think it would make us seem more official, I think it would make us look less appealing.
