### ISSUE TITLE
custom prompt names upon virtualenv creation

### ISSUE THREAD

**Issue by funkybob** [pypa/pipenv#1509]
My team has switched over from pip / requirements.txt to pipenv / Pipfile, and it's mostly been smooth for us.

However, the auto-generated names for venvs that's shown in the prompt is upsetting people's workflows. They feel they're no longer meaningful as they once were.

I assume the original plan was it would adopt the name of the project directory it was in and this be meaningful, but for some environments that doesn't work.
#

**Comment by techalchemy** [comment]
Hi @funkybob, thanks for opening this issue and trying out pipenv. The plan was always to do exactly as we are currently doing, which is to create deterministic virtual environments the location of which is abstracted away from the user.  If you want to manage virtualenvs yourself and only use pipenv for dependency management, you can simply activate a virtualenv before using pipenv (at your own risk, since using `uninstall` will wipe the environment or you could overwrite a pipenv dependency).

The point of pipenv is to prevent users from worrying about their virtualenv locations, and in fact to remove virtualenv activation from your workflows for the most part.  Most command invocation can be done using `pipenv run <command>` and 'activation' so to speak is intended to be done using a pipenv subshell via `pipenv shell`.

The alternative is to have your teams set `PIPENV_VENV_IN_PROJECT` and it will create a `.venv` directory off of the project root.

The pipenv workflow is designed to guide the user to be aware of and working in their project directory, without worrying about what the respective virtualenv is called or where it is.  If you need to have hands-on management of your virtualenvs you probably want to use some other tool to create the environment, since pipenv explicitly is designed to create and manage this for you.

**Comment by funkybob** [comment]
I think I have not explained myself clearly.

Already elsewhere in our project we must create a virtualenv in a specific place, and that is working fine.

I just wanted a way to specify a label used when updating the prompt to show which venv is in use.
Whilst the default makes sense in most cases, it's always nice to be able to override.

As for the PIPENV_VENV_IN_PROJECT env var, I use that in places, but it also means setting a somewhat global setting that I'd rather keep localised. I realise this wouldn't be as simple as making it a command line option, since pipenv would need to always know to look for .venv "just in case".

**Comment by jtratner** [comment]
Next version of pipenv automatically will use .venv if it’s present in the
current directory (already in current master). :)

I don’t fully understand what you mean about a label. If you do something
like:

```
virtualenv my-customvenv-name
source my-customvenv-name/bin/activate && pipenv install
```

pipenv will install into the sourced virtualenv and your prompt should say
`my-customvenv-name` when you source it.

**Comment by funkybob** [comment]
You know how when you activate the virtualenv, it alters your prompt to include the name of the virtualenv in it?

I want a way to control that name it shows.

I guess this is more a virtualenv feature request... but it'd be nice if I could specify it in the Pipfile.

**Comment by kennethreitz** [comment]
feature request == custom prompt names upon creation.

We can do that.

**Comment by kennethreitz** [comment]
it'll be via environment variable though, i don't want more cli flags.

    $ PIPENV_VENV_PROMPT='(custom)' pipenv --three

**Comment by uranusjr** [comment]
[Pew doesn’t support this}https://github.com/berdario/pew/blob/9f64f6c/pew/pew.py#L213), so changes will need to land there first.

**Comment by Darkle** [comment]
So with this new proposed feature, will the custom prompt show up after run `pipenv shell` and are in the shell?

**Comment by Darkle** [comment]
I was actually working on something for this today (assuming its the same thing) for windows: https://github.com/Darkle/pipenv-win-batch-scripts

**Comment by kennethreitz** [comment]
oh, nevermind then

**Comment by uranusjr** [comment]
@Darkle Pipenv already does if you run the shell in compatibility mode (at least on Unix shells; I don’t use `shell` very often and can’t remember the behaviour on ⌘ atm), but otherwise it’s still up to the user to decide whether to display it in the prompt. Your work is still relevant (in certain situations).

**Comment by uranusjr** [comment]
We are recently looking into purging Pew from our implementation. This would be doable once we do that. Stay tuned :)

**Comment by timkofu** [comment]
I'm looking for this feature as well. `python -m venv venv --prompt test_venv` will create a prompt anmed 'test_venv' when the venv is activated, no matter what the venv directory is named.

**Comment by uranusjr** [comment]
Care to try your hands out implementing it? The implementation should be relatively isolated, and would be a nice issue for a new contributor :)

**Comment by timkofu** [comment]
I'll give it a shot.

**Comment by venteto** [comment]
Any updates on whether `python -m venv --prompt [SHORT project name] ...`-style functionality will ever work in `pipenv`?

**Comment by matteius** [comment]
I am locking discussion of this old issue.  Track this issue instead:  https://github.com/pypa/pipenv/issues/1226
FWIW There is a PR out that needs follow-up:  https://github.com/pypa/pipenv/pull/4974

**Comment by matteius** [comment]
New pipenv release `2022.8.5` has been pushed to pypi which covers this feature request.
