### ISSUE TITLE
Clearer messaging about built-in libraries

### ISSUE THREAD

**Issue by roablep** [pypa/pipenv#1542]
It took me a while to realize that I did not need to include system libraries like `json`, `logging` or `os` in the Pipfile. For someone new to virtualenvs and package management, a simple note in the docs or during install telling me these are not needed would have been very helpful.

**Comment by techalchemy** [comment]
Hi @roablep thanks for opening an issue and for using pipenv. Things that are built into the language can’t be installed or pinned to a specific version, and I’m not sure that pipenv is the correct place to document that. You may want to raise that with the python documentation or something like that. I’m going to close this for now but if it comes back up I imagine we would consider it. 

Thanks again!

**Comment by uranusjr** [comment]
A related issue happened to be discussed on the pypa mailing list, that you might be interested in: https://groups.google.com/forum/#!topic/pypa-dev/EZlhpvVfOgs

Basically Pipenv really can’t disallow those package names because *they might actually exist and are what users want*. If this is to be done, it should be somewhere closer to the PyPI index so the maintainer can have more control to the white/blacklist logic. This may be a worthwhile suggestion to raise in the pypa mailing list, so the warning/documentation can be embedded in either PyPI or pip.

**Comment by roablep** [comment]
Good call, thanks. For context, I'm totally new to pipenv and was getting
all sorts of weird errors about why I couldn't install packages like json.
Finally, I launched the pipenv shell and just tried to import them and and
my "ohhhh" moment.
