### ISSUE TITLE
Is it possible to manage site-packages without creating a virtual environment? 

### ISSUE THREAD

**Issue by liuyadong** [pypa/pipenv#1636]
I would like to install some frequently used packages as site-packages, which can be used by many projects without installation. Does pipenv support this feature?

**Comment by kennethreitz** [comment]
pipenv supports this:

    $ pipenv --three --site-packages

**Comment by kennethreitz** [comment]
which will create a virtualenv, and use the python3's interpreter's global site packages as well

**Comment by kennethreitz** [comment]
does that answer your question?

**Comment by liuyadong** [comment]
Yes, thank you. But it would be better to manage global site packages with pipenv.

**Comment by techalchemy** [comment]
Why would you use pipenv for this?

**Comment by techalchemy** [comment]
Pipenv requires an isolated environment to do dependency resolution, it can manage your global site packages as long as you allow it to use a virtualenv to do resolution. If you never want to resolve dependencies or have a virtualenv you should use pip directly because those are the things pipenv adds.

**Comment by liuyadong** [comment]
right, thanks for your explanation.
