### ISSUE TITLE
Using pipenv with a mono-repo and subdirectory dependencies and git causes weirdness

### ISSUE THREAD

**Issue by LegoStormtroopr** [pypa/pipenv#1811]
I am working on a project that uses a mono-repo and want my Pipfile to have subdirectories in that project as dependencies.

If I lock the following `Pipfile`:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
django = "~=1.11"
"aristotle-cloud" = {path = "./python/aristotle-cloud", editable = false}

[requires]
python_version = "3.6"
```

I get the following entry in my `Pipfile.lock`

```
    "default": {
        "aristotle-cloud": {
            "editable": false,
            "path": "./python/aristotle-cloud"
        },

```

But as soon as any git dependency shows up, for example:
```
[packages]
django = "~=1.11"
django-data-importer = {ref = "master", git = "https://github.com/LegoStormtroopr/django-data-importer"}
"aristotle-cloud" = {path = "./python/aristotle-cloud", editable = false}
```

Locking it now produces this entry in the `Pipfile.lock` file:

```
        "aristotle-cloud": {
            "editable": true,
            "git": "https://github.com/LegoStormtroopr/aristotle-cloud",
            "ref": "ccc9b36237fdde97d68cf4b101ca926dbce2aef8",
            "subdirectory": "python/aristotle-cloud"
        },

```

I'm guessing that its picking up the fact that the file is in a git repo, but this isn't what I want. What I want is to lock the Pipfile to still require the subdirectorys when it is checked out, and install all of the packages in it from that directory, not have it go and try and fetch a different commit and install from there (which in this case it can't because its a private repo).

**Comment by techalchemy** [comment]
I'm not sure I understand.  Your pipfile specifies this as a path correctly. Pip however correctly picks up that there are now multiple VCS repositories in play and flags the subdirectory you mentioned (even correctly requiring the subdirectories).  Lockfiles are the same as `pip freeze` roughly speaking, they capture the state of the environment so that it can be _exactly reproduced as it is right now_. If you want to rebuild it from the source materials you use the pipfile, that's the whole point.

When you use a git repository to install things, pip knows about it, so does pipenv.

> What I want is to lock the Pipfile to still require the subdirectorys when it is checked out, and install all of the packages in it from that directory, not have it go and try and fetch a different commit and install from there (which in this case it can't because its a private repo).

I'm having trouble understanding what you are expecting or hoping for.  Roughly, a lockfile captures the current state, including the ref, of any installed objects, including git repositories, subdirectories, etc.  Nothing obligates you to distribute lockfiles if you don't want to pin specific checkouts or versions.  Hope that helps!
