### ISSUE TITLE
Add an option to propagate `--always-copy` to `virtualenv`

### ISSUE THREAD

**Issue by naufraghi** [pypa/pipenv#1929]
Some packages (`sip` from PyQt in my case), are installing some header files in the virtualenv, currently the `include/` folder is symlinked to the system _non-`nt`_ one, and so non writable.

The `virtualenv` script offers the `--always-copy` option (active by default on `nt` systems) to copy all the files.

The `pew` script by default forwards all the unknown arguments to `virtualenv`.

I have the local patch working because I'd like to use `pipenv` in my project.

NOTE: `venv` has a different argument, `--symlinks` / `--copies`, with the same use, but `pew` currently uses `virtualenv`.

- [x] add `--always-copy` option to `pipenv install`
- [ ] add `PIPENV_ALWAYS_COPY` env var
- [ ] add tests

**Comment by naufraghi** [comment]
It's fair enough to know that the suggested solution to this use case is to use the `--system` option and a prebuild virtualenv.

**Comment by uranusjr** [comment]
Considering this only matters during env creation, I don’t think it’s a good idea to implement it as an option (yes I know the same can be said to `--python` etc., but they are regrettably already there). An environment variable is likely the way to go.

**Comment by techalchemy** [comment]
Hmm always copy is different from using global site packages right? So if you didn’t do it at env creation you _couldn’t_ just toggle it on? From an api standpoint we’d want to call this something else since calling a cli flag `—always-x` when you have to pass it in every time you make an env isn’t great. I like the environment approach

**Comment by uranusjr** [comment]
IIRC `--always-copy` means that executables and dynamic libraries are copied from the host installation instead of symlinked.

By default, executables are symlinked on POSIX, and copied on Windows, because Windows symlinks are next to useless. The flag forces virtualenv to copy everything on POSIX as well. I don’t know what the use case is (never used it myself).

**Comment by techalchemy** [comment]
Okay, I'd say lets just leave it alone for now.  Thanks for looking into this and for being thorough, it's a big help!

**Comment by naufraghi** [comment]
Just to avoid some more search:
```
env VIRTUALENV_ALWAYS_COPY=1 pipenv install
```
now does the trick.

**Comment by uranusjr** [comment]
@naufraghi Where do you find the magic command? I was thinking about writing it into the documentation, but cannot find it being used anywhere in Pew, virtualenv, and Pipenv 🤔🤔🤔

**Comment by naufraghi** [comment]
I found the snippet in the linked issue about Vagrant :thinking: :man_shrugging:

**Comment by lucidyan** [comment]
If someone struggling with this nowadays, I found the bug in newer version of `virtualenv`. You should use alias instead of `VIRTUALENV_ALWAYS_COPY`:
```
env VIRTUALENV_COPIES=1 pipenv install
```
More information about flags here:
https://virtualenv.pypa.io/en/latest/cli_interface.html#environment-variables
