### ISSUE TITLE
Sub-dependencies install, even if main dependencies ignored by markers

### ISSUE THREAD

**Issue by murrple-1** [pypa/pipenv#1968]
Tested with version `11.10.0`.

If you setup a dependency with `markers`, the dependency itself honors the `markers`, but its sub-dependencies install anyway. In principle, this probably shouldn't happen, but it's compounded into a real issue when the sub-dependencies themselves fail for reasons stated in the `markers`.

------------

##### Expected result
The sub-dependencies of a dependency should be ignored

##### Actual result
Sub-dependencies are (attempted to be) installed, but (seemingly) only for versions <= 3.3

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate
Please see minimum-reproducible code at [this repo](https://github.com/murrple-1/pipenv-issue-1), with [this Travis-CI](https://travis-ci.org/murrple-1/pipenv-issue-1). Notice that the Pipfile succeeds for Python 3.4, 3.5, & 3.6, but fails for 2.7 & 3.3.

**Comment by techalchemy** [comment]
yeah this is a known issue, we don't propagate markers (intentionally) -- if you have edge cases you have to add markers for their dependencies to your lockfile by hand

sorry for the inconvenience, there may be a case for changing this behavior but I think we would have to be convinced

**Comment by murrple-1** [comment]
Okay, I can do that.

Is there any chance I can request to know the reasoning behind this decision? Alternatively, is there a case to be made for making this more explicit in the documentation? Or is it already explicit in the docs and I just didn't notice the footnote?

**Comment by techalchemy** [comment]
Because often a dependency is skipped mid-way down the dependency chain but only because of a specific marker, but we don't want it to be excluded from the lockfile and we can't know whether the same marker actually does apply to its subdependencies so we don't want to automatically exclude them based on the same criteria.

Implementation is somewhat tricky which is the main reason this hasn't been prioritized, but I can almost guarantee there is nothing in the docs about this.  Feel free to try and find an appropriate place (maybe the common issues page?) and pr something in, it would definitely be appreciated
