### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Meravnext** [pypa/pipenv#2003]
Be sure to check the existing issues (both open and closed!).

Describe the issue briefly here.

Since updating to 10.11.0 Pipenv always fails when creating lock file when downloading its own dependencies (what for?)

Please run `$ python -m pipenv.help`, and paste the results here.

Will not do this, this contains too much private information.

OS is MS Windows, Python is 3.6.5, CPython, official build.

------------

##### Expected result

Lock file created.

##### Actual result

```
INFO:pip9._vendor.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): pypi.python.org
INFO:pip9._vendor.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): pypi.org
INFO:notpip.index:Could not fetch URL https://pypi.python.org/simple/autopep8/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833) - skipping
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches autopep8
Tried: (no version found at all)
```

1. This should be an error, not a warning (Pipenv failed to do everything it was asked, how is this a warning?)
2. What changed? Why are there two different PEM files in Pipenv sources and ssl.py is still using neither? What were you trying to achieve by manipulating these certificates?

##### Steps to replicate

I haven't yet seen any Pipenv version 10.11.0 that would work on MS Windows... just run it on one?

The problem doesn't exist on Linux with the same versions. Bare PIP install works, the URL it is trying to access is accessible to every HTTP client I tried (a bunch of browsers, Cygwin version of curl and wget, Putty's telnet).  I'm still debugging ssl.py to try to get a better error report, but this is really difficult due to how pipenv's code is using it, so I may not get better info.

**Comment by Meravnext** [comment]
https://github.com/python/cpython/blob/3.6/Modules/_ssl.c#L833 this is the line 833 which reports the error. This seems to suggest (if this is the correct version of the source) that it is trying to do async I/O on this socket, but it cannot do this because it's not supported. 

If you believe that you made any changes which resulted in using async I/O on MS Windows sockets, you probably need to undo that.

**Comment by techalchemy** [comment]
Hi.  There was an issue with the pypi infrastructure this morning. 

> If you believe that you made any changes which resulted in using async I/O on MS Windows sockets, you probably need to undo that.

We didn't.

**Comment by wvxvw** [comment]
Well, you added a bunch of dependencies, through which you might have inadvertently do this.  (The posts above are mine, I was using co-worker's computer trying to understand the problem, and didn't notice it wasn't my account).

Regardless of your attitude, the problem is very real. It is also not connected to the recent outage in PyPI, nor to the update of PIP version.  It is something you added in between versions 9.0.3 and 10.11.0.

**Comment by techalchemy** [comment]
It was connected. Please be productive and polite or be on your way. Once again I will refer you to the code of conduct.

Jumping to the conclusion that we have made changes to something w/r/t asyncio on windows without any basis besides an SSL error when you had a connection issue at _precisely_ the same time when PyPI had infrastructure issues and lots of other people had SSL and redirection errors, that's a bit of a leap.

> I haven't yet seen any Pipenv version 10.11.0 that would work on MS Windows... just run it on one?

I develop and run pipenv on windows. Remarks like this are not going to get you any further support, so basically we have 2 options:

1) You can report issues by filling out the detailed issue template and, rather than making comments about how you've never seen our free, volunteer software work, you can provide helpful and informative information;

2) You can instead continue with the approach of opening issues and questioning why we have made changes or design decisions, telling us what our messages should say, asking whether anyone has ever seen a working version of this software, and accusing us of a slew of things based on your hunch, and providing no helpful debugging information (not for the first time I might add)

I'm sure you can understand why the second choice isn't one we welcome; I will again refer you to the code of conduct and defer to @ncoghlan in case he has any further input.

I would like to note that if you're using pipenv 10.11 as you say, you should probably upgrade to 11.10

**Comment by wvxvw** [comment]
I don't care about your code of conduct. I just need enough evidence to convince my boss to drop your project from the list of things we need to support.  You've been very helpful in that as of so far.

**Comment by wvxvw** [comment]
OK. This is not your fault. This is this "improvement" https://bugs.python.org/issue33127
