### ISSUE TITLE
Better error message if a pre dependency is not found

### ISSUE THREAD

**Issue by bitwave** [pypa/pipenv#2019]
I use pipenv --two
and pipenv install angr aborts with:

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches capstone>=3.0.5.rc2
Tried: 2.0, 2.1, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5rc2, 3.0.5rc2, 3.0.5rc2, 3.0.5rc2, 3.0.5rc2

```

**Comment by bitwave** [comment]
pipenv lock --pre works, but an useful error would be awesome

**Comment by uranusjr** [comment]
I agree the message can be improved. Can you modify the title to make the scope clear?

**Comment by techalchemy** [comment]
The reason the message is generic is because it handles basically any case where resolution fails. We can build additional logic for messaging but I feel I’m so far removed from the UX here that I’m not even sure what would be helpful

**Comment by techalchemy** [comment]
Excellent suggestion

**Comment by bitwave** [comment]
added a pull request

**Comment by meshy** [comment]
I'm seeing a similar issue.

I'm looking at using a project with pipenv, but some dependancies clash, and it's not immediately clear where the issue is coming from:

`Could not find a version that matches Django<1.10,>=1.11`.

(I've cut out a few versions, as these are those that clash.)

It would be very helpful if the lines in the `requirements.txt` I'm importing (or the subpackages) were listed along each of the required versions.

**Comment by techalchemy** [comment]
This case is more complicated and I’m not sure it can be easily resolved
