### ISSUE TITLE
`pipenv shell` fails with msys

### ISSUE THREAD

**Issue by thewtex** [pypa/pipenv#2042]
`pipenv shell` fails in an [msys2](https://www.msys2.org/) shell:

```
../Python36/Scripts/pipenv shell                                                              │
zsh:1: command not found: c:python36python.exe 
```

Please run `$ python -m pipenv.help`, and paste the results here.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.0'`

Pipenv location: `'C:\\Python36\\lib\\site-packages\\pipenv'`

Python location: `'C:\\Python36\\python.exe'`

Other Python installations in `PATH`:

  - `2.7`: `C:\msys64\usr\bin\python2.7.exe`
  - `2.7`: `C:\msys64\usr\bin\python2.7.exe`
  - `3.6`: `C:\msys64\mingw64\bin\python3.6m.exe`
  - `3.6`: `C:\msys64\mingw64\bin\python3.6.exe`
  - `3.6`: `C:\msys64\usr\bin\python3.6.exe`

  - `3.6.2`: `C:\msys64\usr\bin\python.exe`
  - `2.7.13`: `C:\msys64\usr\bin\python2.exe`
  - `3.6.4`: `C:\msys64\mingw64\bin\python3.exe`
  - `3.6.2`: `C:\msys64\usr\bin\python3.exe`
  - `3.6.5`: `C:\Windows\py.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.16299',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

System environment variables:

  - `!;`
  - `ACLOCAL_PATH`
  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CCACHE_COMPRESS`
  - `COMMONPROGRAMFILES`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONFIG_SITE`
  - `CONTITLE`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `EDITOR`
  - `EXTERNALDATA_OBJECT_STORES`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `GPG_TTY`
  - `GREP_COLOR`
  - `HISTCONTROL`
  - `HISTFILE`
  - `HISTSIZE`
  - `HISTTIMEFORMAT`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HOSTNAME`
  - `INFOPATH`
  - `LANG`
  - `LESS`
  - `LOCALAPPDATA`
  - `LOGNAME`
  - `LOGONSERVER`
  - `LP_RUNTIME_THRESHOLD`
  - `LS_COLORS`
  - `MANPATH`
  - `MINGW_CHOST`
  - `MINGW_PACKAGE_PREFIX`
  - `MINGW_PREFIX`
  - `MSYSCON`
  - `MSYSTEM`
  - `MSYSTEM_CARCH`
  - `MSYSTEM_CHOST`
  - `MSYSTEM_PREFIX`
  - `NUMBER_OF_PROCESSORS`
  - `OLDPWD`
  - `ORIGINAL_PATH`
  - `ORIGINAL_TEMP`
  - `ORIGINAL_TMP`
  - `OS`
  - `ONEDRIVE`
  - `PATH`
  - `PATHEXT`
  - `PKG_CONFIG_PATH`
  - `PRINTER`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMFILES`
  - `PROMPT`
  - `PS1`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PWD`
  - `PROGRAMDATA`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `SAVEHIST`
  - `SESSIONNAME`
  - `SHELL`
  - `SHLVL`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TERM`
  - `TMP`
  - `TMUX`
  - `TMUX_PANE`
  - `USER`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VIRTUALENVWRAPPER_VIRTUALENV_ARGS`
  - `VS140COMNTOOLS`
  - `WD`
  - `WINDIR`
  - `WORKON_HOME`
  - `_`
  - `_JAVA_OPTIONS`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenvspecific environment variables:

Debugspecific environment variables:

  - `PATH`: `C:\msys64\home\mingus\bin\exe;C:\msys64\home\mingus\.cargo\bin;C:\msys64\home\mingus\.npm-global\bin;C:\msys64\home\mingus\.config\dotfiles\bin;C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\usr\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl`
  - `SHELL`: `C:/msys64/usr/bin/zsh`
  - `EDITOR`: `C:/msys64/usr/bin/vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `C:/itk-jupyter-widgets`

---------------------------

------------

##### Expected result

The shell environment to be activated.

##### Actual result

It appears that the wrong path separators are used?

##### Steps to replicate

- Installed msys2
- Using zsh
- Installed Python 3.6 from Python.org
- Installed the pipenv package

**Comment by techalchemy** [comment]
- Pipenv doesn't support msys on windows (officially)
- Use `pipenv run` instead
- We use the correct path separators because we don't do checks for if you use linux emulation on windows
- This might work if you used `../Python36/Scripts/python -m pipenv shell` but I have no idea

Our software stack is super complicated already since we handle random stuff like this, in addition to dependency management/environment management/dependency resolution across platforms and python versions, which is why we kind of draw the line there. The overhead of maintaining the codebase so it works not just across these platforms but in addition has to recognize when it runs in a partial emulation implementation is too much overhead for a development team of our size.

That said, if someone has a simple fix for this I'm sure we'd be willing to review it

For reference we are just using python's separators here I believe.  I'm gonna close this for now since fixing it is not on the roadmap and isn't likely to make it on a priority list anywhere, FWIW I'd just use `pipenv run` (I do this myself, I don't really ever use `pipenv shell` in my workflow)
