### ISSUE TITLE
PPA for Ubuntu 16.04 Xenial Xerus

### ISSUE THREAD

**Issue by dneuhaeuser-zalando** [pypa/pipenv#2059]
Any chance of getting a PPA for Ubuntu 16.04? Given that this is the latest LTS I imagine that there are probably quite a few other people who'd like support for this.

**Comment by techalchemy** [comment]
I can’t trigger pypa ppa builds but I’ll see what I can do

**Comment by salmanulfarzy** [comment]
PPA also not available to Ubuntu 18.04 LTS Bionic Beaver.

**Comment by hiimdoublej** [comment]
Can confirm, ppa not working in 18.04 , same output as @salmanulfarzy

**Comment by rfoliva** [comment]
I have just been able to install it on Ubuntu 18.04 via PPA repo by using the artful codename, instead of the bionic one. I have not used it for long, but it seems to be fully functional so far. So it should not be so hard to get the bionic one in place, but of course this would require complete set of tests. I would be happy to help working on getting that to the repo, or assisting maintaining current list of supported Ubuntu versions there. I think current LTS ones and also ongoing testing version would help getting more users onboard with pipenv.

**Comment by uranusjr** [comment]
I guess there is simply not enough interest in the team to pursue this. Feel free to set up your own PPA; we’ll be happy to mention it :)

**Comment by slhck** [comment]
@uranusjr Are you referring to 16.04 only? A PPA for 18.04 (and corresponding instructions in the `README` etc.) would make sense given that this is the latest LTS now and 17.10 will be eventually EOL'd.

Otherwise I'd recommend telling people to use `pip` to install `pipenv`, and removing the PPAs from the `README`.

**Comment by uranusjr** [comment]
@slhck No I’m referring to Ubuntu in general. I think pip is in fact *the* preferred installation method by the Python community, and should be recommended in any case. The PPA thing is only nice-to-have-if-you-really-prefer-this.

**Comment by slhck** [comment]
Ah, I understand, thanks for the clarification.

In that case I would recommend to remove the PPA instructions from the Readme, or at least make it more obvious that `pip` is preferred. Right now it says:

> Or, if you're using Ubuntu 17.10:
> 
>     $ sudo apt install software-properties-common python-software-properties
>     $ sudo add-apt-repository ppa:pypa/ppa
>     $ sudo apt update
>     $ sudo apt install pipenv
> 
> Otherwise, just use pip:
> 
>     $ pip install pipenv

Which would get most users to automatically try the PPA method.

**Comment by altendky** [comment]
Live on `docs.pipenv.org` but not on PyPI.  The README.rst is separate...  :|

https://github.com/pypa/pipenv/blob/e937d85515b457e2bfb46a57c0bd637c4c057420/README.rst
https://github.com/pypa/pipenv/blob/e937d85515b457e2bfb46a57c0bd637c4c057420/docs/index.rst

We're certainly straying from a 16.04 PPA, but...  pyenv is a bit much for this.  You only need a virtualenv or venv.  Even with a pyenv'ed Python, virtualenv/venv are still proper since they solve problems other than just the hazard of destroying your OS.

**Comment by altendky** [comment]
Or perhaps a build step was just missed to regenerate the `index.rst`?  The generated comment says January 30.

**Comment by slhck** [comment]
@altendky Actually I was talking about the README on GitHub, which is (at least for me) the first place where I look up how to install pipenv.

**Comment by altendky** [comment]
@slhck yeah, I got it backwards.  The `docs/index.rst` is updated and the `README.rst` is not.

**Comment by uranusjr** [comment]
Pull requests accepted 🎵

**Comment by escorciav** [comment]
Hi! any update?

I'm stuck trying to build a 3rdparty legacy project using Ubuntu 16.04... one of the multiple dependencies is grabbing its new version which happens to demand python3.6. Thus, I need development batteries to build that 😓

**Comment by escorciav** [comment]
I'm OK with the step by step guide on how to

- install pipenv

- make pipenv visible "to everyone" within a docker image

I know how to hack it for my box and my project, but this legacy project has a bunch of stuff that I'm afraid it can break other projects in my box.

**Comment by techalchemy** [comment]
I am planning to at least publish a snap of pipenv in the near future, and I will take a shot at republishing a new deb. That may be a bit difficult due to unvendoring challenges.

**Comment by escorciav** [comment]
No worries. I got confused, due to the name of the programs 😅 , I was lloking for `pyenv` 😆 . 

Thanks for replying back, stay safe and healthy!
