### ISSUE TITLE
pipenv install -e . is not documented

### ISSUE THREAD

**Issue by yrro** [pypa/pipenv#2106]
`pipenv` recommends running `pipenv install -e .` to install a local setup.py into the venv. But it is not documented when running `pipenv install --help`.

**Comment by techalchemy** [comment]
Thanks for the feedback. The help command gives a general overview and covers what each subcommand does. Being a terminal with limited space jts just not practical to cover usage examples for every command. `-e` is just ‘editable’ according to setuptools and pip, and only works for VCS dependencies. `.` is obviously a filesystem path but could be any path.

Closing for now since this just isn’t that practical I think

**Comment by danielcompton** [comment]
FWIW I was confused by this too and went looking at `--help` to see if I could find any reference to it.

> `-e` is just ‘editable’ according to setuptools and pip, and only works for VCS dependencies

I don't quite understand why this couldn't be documented in pipenv, it seems like it's a pipenv command, so it should also have documentation there? I can agree with not putting the full documentation and examples of `pipenv install -e .`, but it seems like it would be useful to have documentation for all command line flags that you could pass to a command? Perhaps I'm missing something?

**Comment by uranusjr** [comment]
If someone writes a documentation page on the detailed usages of the command, we can add a link to the help message, but I don’t think this is suitable in the message itself.
