### ISSUE TITLE
Provide changelog

### ISSUE THREAD

**Issue by ovalseven8** [pypa/pipenv#2143]
Please add a `CHANGELOG.md` file and document the version changes.

**Comment by gsemet** [comment]
Maybe pipenv can use [reno](https://docs.openstack.org/reno/latest/) to document a release note easily ? I use it on Guake for the [NEWS](https://github.com/Guake/guake/blob/master/NEWS.rst) and [online release note](http://guake.readthedocs.io/en/stable/project/release_notes.html), quite fascinating how it works!

**Comment by greysteil** [comment]
Did you see https://github.com/pypa/pipenv/blob/master/HISTORY.txt?

✌️

**Comment by ovalseven8** [comment]
@greysteil: Oh, sorry. I did not see it. Perhaps you should rename it to "CHANGELOG", it's more clear what the content will be IMHO. :)

**Comment by techalchemy** [comment]
I don’t really see a need to name it differently. This is a perfectly acceptable name

**Comment by sblancov** [comment]
Investigating a little about this topic, I have found this:
https://keepachangelog.com/en/1.0.0/

Copying the second question of the FAQ and its answer:

> **What should the changelog file be named?**
> Call it CHANGELOG.md. Some projects use HISTORY, NEWS or RELEASES.
> 
> While it's easy to think that the name of your changelog file doesn't matter that much, why make it harder for your end users to consistently find notable changes?

Probably that reason is a good reason to change it because at least one person have not found the change log of this project despite of it exists (see first message of this issue).

"HISTORY.txt" is an acceptable name, but it seems it is not a [foolproof](https://en.wikipedia.org/wiki/Idiot_proof) name.

**Comment by techalchemy** [comment]
That’s good to know. We will take it into consideration.
