### ISSUE TITLE
Package in private repo with same name as one from Pypi

### ISSUE THREAD

**Issue by prcastro** [pypa/pipenv#2159]
I have a package in a private repository with the same name as one from PyPi. The PyPi one, having a higher version number, always get installed.

```
[[source]]
url = "https://pypi.myrepo.com.br/pypi"
verify_ssl = true
name = "myrepo"

[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
mypkg = ">=0.0.1"

[requires]
python_version = "3.6"
```

Is there a way to define that a package comes from a certain private repo?

**Comment by prcastro** [comment]
Just found the info in the docs

**Comment by prcastro** [comment]
I'm reopening since even specifying `mypkg = {version: ">=0.0.1", index="myrepo"}` on the `Pipfile`, `pipenv` installs the version from `pypi`.

```
pipenv, version 11.10.1
```

**Comment by techalchemy** [comment]
if you leave an open pin it will always find the best candidate, i.e. the one at the highest version number in any of the indexes you have available, which was the behavior we settled on (since that's how pip handles `--extra-index-url` and that's what we do with the additional `sources`).  If you add a strict pin the problem goes away.  I'd be willing to consider ways to modify the behavior here though

**Comment by uranusjr** [comment]
Related discussion pypa/pip#3454

**Comment by prcastro** [comment]
I would find more intuitive to always search in the source order defined in the Pipfile, unless a specific index is specified on the dependency.

In my case `mypkg = {version: ">=0.0.1", index="myrepo"}` would only search in `myrepo` while `mypkg = ">=0.0.1"` would search first in `myrepo` and then in `pypi`, getting the newest version, since this is the source order defined on the Pipfile.

However, maybe one would like to change the source order in a per-dependency basis. Then, one could add a `extra_index` key, so `mypkg = {version: ">=0.0.1", index="pypi", extra_index="myrepo"}` would search first on `pypi` and then on `myrepo`.

**Comment by techalchemy** [comment]
@prcastro that’s exactly what we do now. The challenge is if the same package has a higher version in the second repository that will be selected. You would need to only search one repository which isn’t supported by any syntax yet

**Comment by seglberg** [comment]
This seems to be the same/similar issue I raised in #2102. Personally I think the current syntax is confusing because when I specify `mypkg = {version: ">=0.0.1", index="myrepo"}` I logically expect it to use `myrepo` only and disregard pypi.

**Comment by fridex** [comment]
> Personally I think the current syntax is confusing because when I specify mypkg = {version: ">=0.0.1", index="myrepo"} I logically expect it to use myrepo only and disregard pypi.

This is exactly what I would expect as well. Based on the linked discussion to pypa/pip#3454 it does not seem viable to have such ability in pip itself. As pipenv tries to be a better tool, I think incorporating such change would be really helpful.

I haven't looked into sources how big the given fix would be, but I guess for the

**Comment by uranusjr** [comment]
Pipenv does not aim to be a better tool than pip, in the sense of doing the same things it does, but better. We aim to provide a better user interface than direct pip (and virtualenv) usages. The difference is that we still leverage largely against pip functionalities, without re-invent the wheels.

We will be very interested in adapting an alternative installing method if there is one, however. I look forward to the contribution :)

**Comment by reinout** [comment]
If I read the documentation (https://pipenv.readthedocs.io/en/latest/advanced/#specifying-package-indexes), it says

> If you’d like a specific package to be installed with a specific package index, you can do the following:

The example code is:

    [packages]
    requests = {version="*", index="home"}
    maya = {version="*", index="pypi"}

The suggestion from the documentation is that `index=` can be used to install a package with that *specific* index.

When I do tests with two indexes, pipenv always calls pip with `-i first_index --extra-index-url second_index`. If I specifiy `index=`, it doesn't seem to make any difference.

`index=` doesn't seem to add the mentioned index as `--extra-index-url`, as both indices are passed to pip anyway. Likewise, it doesn't restrict the index used.

So: it doesn't do what the documentation suggests. Perhaps the documentation needs to be re-worded. But re-wording the documentation is hard as `index=` doesn't seem to be doing anything at all :-)

Am I missing something? I've looked in the code and I cannot find where the `index=` would be used. I *do* see the main `project.sources` being used.

**Comment by fridex** [comment]
> So where do you think this could/should be changed? Is it in the locking part? Or in the sync-part?

The crucial thing that would need to change is treating indexes as mirrors, a logic change would require switching to treating them as separate sources of packages. This is not something that is that is easy to solve given the current architecture of package resolution mechanism, [upstream Python packaging statement](https://github.com/pypa/pip/issues/3454) and the configuration (not speaking about Pipenv here, but rather pip itself). The question is then how the transitive dependencies could be resolved, how to configure cross-index resolution, ... (which index takes precedence? can these indexes be mixed?).

This is something we were fighting with, finally we decided to create a mechanism on top of Pipenv (Pipfile and Pipfile.lock configuration) that would check for provenance/origin of installed packages. It's open source, you can find it [here in the Thoth project ](https://github.com/thoth-station/adviser#provenance-checks) (feel free to use/comment/contribute/...).

**Comment by techalchemy** [comment]
@fridex you can also just specifically say `--pypi-mirror` or set `PIPENV_PYPI_MIRROR` for our purposes.  But otherwise you are articulating a pretty thorough depiction of the problem, because even if we find the package in the specified index, it's a toss-up whether we find its dependencies there.

@prcastro 
With regard to having your  indexes ignored, it has more to do with how packages are accumulated and sorted.  If a package comes from the secondary search index (in this case, normal PyPI) but still has the 'best match' version, it gets preferentially sorted.  If there are two equivalent candidates, the primary index takes priority.

Basically if you specify indexes pip is still going with the best candidate no matter what, and simply leaving other indexes out isn't that straightforward.  If you don't want the best candidate, you can pin something specific (this is how things are currently)

Myself and @uranusjr would be willing to consider alternatives (@fridex may have the best understanding of how this might be implemented) but it would have to take these into account, and honestly I'd prefer to see it [written as an enhancement proposal](https://github.com/pypa/pipenv/blob/master/peeps/PEEP-001.md) so we can start fleshing out what the logic looks like. That would help us keep it clear going forward.

I'll keep this open for now but that seems like the right way forward besides checking out the referenced project

**Comment by gitpushdashf** [comment]
Do you have any update on this? I'm running into it as well.

**Comment by dd-ssc** [comment]
Hmmm... about a year later and still no update ?

I'm running into this as well - with a bit of a twist: Everything works fine on my local MacBook, but fails when creating the same venv on a Linux host with the same environment.

Any workarounds for the time being ?

**Comment by matteius** [comment]
I believe this is solved with index restricted packages.   What version of `pipenv` are you on @dd-ssc  and are you explicitly specifying your index in the `Pipfile`?  Please see:   https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes
