### ISSUE TITLE
Free as in Freedom?

### ISSUE THREAD

**Issue by pedrocunial** [pypa/pipenv#2221]
Hey there!

I've been browsing through this project and I gotta say I actually really admire what you guys have been doing, however, one thing that really intrigues me is the fact that you guys used the GPL "slogan" (free as in freedom) to describe it, when it isn't in fact a free (as in freedom) project, since it is under the MIT license.

Anyway, it was just something that was really bugging me out and I could not find anything similar on any recent issue (opened and closed).

🥂 

Pedro

**Comment by uranusjr** [comment]
Truth be told, I never really understood how Richard Stallman and GNU really defines free (libre). From what I can gather, however, is that while free software is the goal of GNU (and Richard Stallman), and the GPL (and friends) is designed to enforce the freedom, there is no indication that other Open Source licenses do not qualify as free (libre).

Primary sources include:

* [*What is free software?*](https://www.gnu.org/philosophy/free-sw.html) — MIT (and thus Pipenv) fits all the bullet points, as far as I can tell.
* [*Why Open Source misses the point of Free Software*](https://www.gnu.org/philosophy/open-source-misses-the-point.html) — Quote: *Nearly all open source software is free software, but there are exceptions.* There is no mention what exactly are exceptions (or what are not), but judging from the general open source license spectrums, I’d guess MIT qualifies as free. Again, there are no description in this article to suggest otherwise.

I am closing this issue because the argument lacks solid grounds in my view. Feel free to reopen if you can find direct, creditable sources to support your doubts.

**Comment by OrangeDog** [comment]
The GNU project lists this license under [GPL-Compatible Free Software Licenses](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).
It should therefore be considered at least as "free" as the GPL is.
