### ISSUE TITLE
Specifying the project/Pipfile location as a command line argument

### ISSUE THREAD

**Issue by dansanderson** [pypa/pipenv#2237]
As far as I can tell, the pipenv command line tool always derives the project directory (Pipfile location) from the current working directory. Is there a way to tell pipenv which project directory to use as a command-line option? If not, is this a compelling feature request?

In my use case, I want to determine the venv path for a project from a script. I'd prefer not to change the current working directory just to invoke `pipenv --venv` in a shell process. Is there a stable API for doing this directly from Python? (Whereas the feature request to accept a project dir on the command line would be a similar API for shell scripting.)

**Comment by techalchemy** [comment]
There is a tool called `pipenvlib` which we don't spend a lot of time on but  if you want to do this from a shell process you can temporarily set `PIPENV_PIPFILE` to point at the Pipfile of the relevant project and run `pipenv --venv` :

```shell
 ~/g/pypa-pipenv   master $…  set -gx PIPENV_PIPFILE /home/hawk/git/requirementslib/Pipfile
 ~/g/pypa-pipenv   master $…  pipenv --venv
/home/hawk/.virtualenvs/requirementslib-5MhGuG3C
 ~/g/pypa-pipenv   master $…  set -e PIPENV_PIPFILE
 ~/g/pypa-pipenv   master $…  pipenv --venv
/home/hawk/.virtualenvs/pypa-pipenv-PuUpLSqX
```

**Comment by tobiasb** [comment]
For anyone stumbling upon this, there is (now) an environment variable `PIPENV_PIPFILE` which let's you specify the location of the Pipfile. See https://pipenv.pypa.io/en/latest/advanced/

```
PIPENV_PIPFILE

If set, this specifies a custom Pipfile location.

When running pipenv from a location other than the same directory where the Pipfile is located, instruct pipenv to find the Pipfile in the location specified by this environment variable.

Default is to find Pipfile automatically in the current and parent directories. See also PIPENV_MAX_DEPTH.
```

**Comment by zoodiabloc** [comment]
@tobiasb Out of curiosity is there a way to set the Pipfile path as a command line parameter of pipenv run? If there are multiple different pipenv projects that need to run at the same time, it will be hard setting `PIPENV_PIPFILE` to all of them.

**Comment by tobiasb** [comment]
@zoodiabloc you can pass the env bar to the call to `pipenv` directly, e.g.

```
PIPENV_PIPFILE=path/to/pipfile pipenv run ...
```

**Comment by zoodiabloc** [comment]
Cool it worked! Thanks!

**Comment by e4z9** [comment]
A --pipfile command line argument would be greatly appreciated.

I'm running a python script that I can pass another command for a subtask, and that command is another python script that requires pipenv to run. If I use the environment variable, I need to set it before running that first python script, which might need a different pipenv than the command that I pass. I cannot pass the environment variable as part of the command that I pass to the first script, because "PIPENV_PIPFILE=path/to/pipfile pipenv run ..." relies on a Unix SHELL. I'm also using this cross-platform on Windows, Linux and macOS, so solutions relying on a Unix SHELL, shebang lines etc do not help.
