### ISSUE TITLE
Add `pipenv add PACKAGE` sub command which replace `pipenv install PACKAGE`

### ISSUE THREAD

**Issue by doloopwhile** [pypa/pipenv#2266]
**Is your feature request related to a problem? Please describe.**  
`pipenv install` has two responsibilities:

- Install all packages in `[packages]` (bare `pipenv install`)
- Install specified package and update `Pipfile` and `Pipfile.lock`  (`pipenv install PACKAGE`)

This make confused beginners.

**Describe the solution you'd like**  
I suggest to add `pipenv add PACKAGE` which is equivalent to `pip install PACKAGE`
and to make `pipenv install PACKAGE` deprecated.

**Describe alternatives you've considered**  
Just remove `pipenv install PACKAGE`.

We are able to edit Pipfile If we want to add package.

**Additional context**  

- `yarn` provides `yarn add PACKAGE` correspond to `pipenv install PACKAGE`. `yarn install PACKAGE` was removed.
- `bundler` does not provide sub command correspond to `pipenv install PACKAGE`

**Comment by uranusjr** [comment]
Slightly related: This may be a good chance to clarify what is the fate of `install` (no arguments) going forward. If `add` is adopted, it is probably best to clean up `install` to remove the overlapping functionalities it shares with `sync`.

**Comment by techalchemy** [comment]
Internally the overlap should be cleaned up. From an api perspective, most users want to use high level commands like install so removing api functionality merely because of overlap seems unnecessary. 

I’ll run this by Kenneth and see where we land. Initial pass on the workflow is intuitive enough.

**Comment by phoikoi** [comment]
It seems to me that keeping with the way pip works (i.e. `pip install PACKAGE`) would be a logical thing for pipenv, rather than imitating yarn, npm, bundler, etc.

**Comment by uranusjr** [comment]
@philfreo Pipenv works quite differently than pip in concept, however. `pipenv install` does a lot more than `pip install`—it also adds the package into Pipfile, and updates Pipfile.lock. The verb `install` is also used in `pipenv install` (no arguments), which means “updates Pipfile.lock from Pipfile, and installs all packages in Pipfile.lock”, which is quite different from `pipenv install <package>`. `install` is a traditionally more used verb, but `add` is picking up popularity recently to disambiguous the action from the sterotypical “install” action, even in languages with well-established manifest-lock terminology (e.g. Yarn vs NPM).

I would even say you solidified the reasoning to favour `add` by misidentifying the naming implication :p

**Comment by techalchemy** [comment]
I generally tend to agree, there is basically no chance we will ever remove `install`. In my view that is not on the table. `pipenv add package`, if it were a CLI interface, would need to perform the intuitive action of adding the package to your Pipfile _without_ installing it (i.e. in contrast to `pipenv install`).  And while yarn and bundler may behave a certain way, `pipenv` is operating within an ecosystem which has had packages governed by an `install` verb for decades -- I don't see a good design reason to try and change that now just because some pieces of other communities have axed the `install <package>` option.  I also don't fully understand why they have chosen to take that approach

And while `yarn` doesn't have an `install` command, `npm` does; where `bundler` lacks one, `RubyGems` has one.  I'll note here that `cargo` provides an install command, etc etc.  It's just not really a valid way of arguing the point of keeping or getting rid of a command.  As for the use case for adding something to the pipfile but not installing it, I can see the possibility but I am guessing this isn't that high a priority

**Comment by techalchemy** [comment]
Yeah to clarify my position on this now since we kind of commented at the same time, I have no qualms with having `pipenv install` and also `pipenv install <package>` but I do wonder about a separate verb if you want to interact with the file itself

**Comment by techalchemy** [comment]
Also apologies, misclicked :)

**Comment by uranusjr** [comment]
@techalchemy Yarn does have `install`. `yarn install` is synonymous to `yarn` without arguments.

**Comment by kennethreitz** [comment]
this is not happening
