### ISSUE TITLE
pipenv install shows "ERROR: virtualenv is not compatible with this system or executable"

### ISSUE THREAD

**Issue by CheHaoKang** [pypa/pipenv#2291]
When I type **pipenv install**, it shows:
![image](https://user-images.githubusercontent.com/16597735/40869541-a8bfab24-664f-11e8-824a-92d14ff637ea.png)

I googled many websites but not found any solutions.

The steps are similar to PyCon slides (**compile Python, install pipenv in venv**)::
**1. git clone https://github.com/python/cpython.git
2. git checkout 3.6
3. mv cpython python
4. ./configure --prefix=$HOME/.local/python
5. make
6. sudo make install
7. mkdir -p ~/.local/bin ~/.local/venvs  
8. ln -s ~/.local/python/python ~/.local/bin/python3.6
9. ln -s ~/.local/bin/python3.6 ~/.local/bin/python3
10. vi ~/.bashrc
`alias python3='/home/deckenkang66/.local/bin/python3'`
11. OPEN a new terminal
12. python3 -m venv ~/.local/venvs/pipenv  
13. ~/.local/venvs/pipenv/bin/pip install pipenv  
14. ln -s ~/.local/venvs/pipenv/bin/pipenv ~/.local/bin  
15. pipenv --version
`pipenv, version 2018.05.18`
16. pipenv install**

Thanks.

**Comment by uranusjr** [comment]
Where are you installing Python? It seems like you installation is broken. The compile steps are strange too—you `sudo make install`, which by default would link your Python executable to `/usr/local/bin`, but then you link your Python from `~/.local`. My guess is your installing Python wrong in step 7–9. Not a problem in Pipenv.

**Comment by MichaelKim0407** [comment]
I'm having a similar issue as well

@uranusjr `./configure --prefix=$HOME/.local/python` would install python in `~/.local`

**Comment by uranusjr** [comment]
At least add your configure output or there’s nowhere to start. The error message is quite clear: Your environment is not compatible. This means you are missing something during compilation.

Please provide actionable information.

**Comment by MichaelKim0407** [comment]
I have a working `python` installation and everything in the standard library works correctly. The way OP installed his python is also legit and there's nothing wrong in it. I was merely pointing it out.

After some searching it's a `virtualenv` problem: https://github.com/pypa/virtualenv/issues/1051 and by extension, a `pipenv` problem because it chooses to use `virtualenv`.
So if you want "actionable information", don't use `virtualenv`. But since you made clear in #15 you won't switch away from `virtualenv`, I guess there's no point in continuing this discussion.

**Comment by uranusjr** [comment]
I am not saying the *Python* installation isn’t legit. Not every Python installation works with virtualenv, and since CPython does environment sniffing during compilation, it is not possible to know exactly what causes your installation to not work without knowing how your environment is configured. To provide a constructive way to proceed, you need to either provide a reliable way to reproduce the error; otherwise the maintainers can’t offer much help, since the same compilation process appears to work for many people, including myself.

**Comment by MichaelKim0407** [comment]
As I said, it's a dependency issue. If you are interested in the details, there is a link above.

I would think that the most important information for you as a package maintainer is that your dependency doesn't work for some people.
