### ISSUE TITLE
Homebrew-installed Pipenv defaults to Homebrew-created virtualenv Python

### ISSUE THREAD

**Issue by aweimeow** [pypa/pipenv#2296]
As following log, it will use `/usr/local/Cellar/pipenv/2018.5.18/libexec/bin/python3.6`, instead of use system installed python

```
🚀  pipenv install --dev
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
Using /usr/local/Cellar/pipenv/2018.5.18/libexec/bin/python3.6 (3.6.5) to create virtualenv…
⠋Already using interpreter /usr/local/Cellar/pipenv/2018.5.18/libexec/bin/python3.6
Using real prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/aweimeow/pipenv/.venv/bin/python3.6
Also creating executable in /Users/aweimeow/pipenv/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/aweimeow/pipenv/.venv
Installing dependencies from Pipfile.lock (ae475c)…
Ignoring colorama: markers 'sys_platform == "win32"' don't match your environment
Ignoring configparser: markers 'python_version < "3.2"' don't match your environment
Ignoring enum34: markers 'python_version < "3.4"' don't match your environment
Ignoring funcsigs: markers 'python_version < "3.0"' don't match your environment
Ignoring stdeb: markers 'sys_platform == "linux"' don't match your environment
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 55/55 — 00:00:42
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

**Comment by uranusjr** [comment]
This is *kind of* expected because Pipenv defaults to use the Python it is installed to when you do not specify `--python` (or two or three). This is however especially problematic in Homebrew’s case because Homebrew *always* installs each package version in a virtualenv, and the old one will break when you upgrade and do cleanup (`brew purge`).

This is not a Pipenv bug per-se, but we’ll probably want to improve the Homebrew experience if we support it has a first-class installation method. One simple solution would be to remove the auto-Python-detection outright, and *requires the user to specify a Python when initialising an environment*.

**Comment by techalchemy** [comment]
@uranusjr I just pushed up a bunch of changes to https://github.com/sarugaku/pythonfinder which simply use the user path order to find python, unless a version is supplied.  We could swap to that (which has been the plan all along) once we are happy with it

**Comment by uranusjr** [comment]
@nathanielford This is *not* related to the top issue. It is a long-standing Homebrew problem around Python formulae. Due to how they manage Python installations, every Python package formula would break every time you upgrade Homoebrew Python, until a new revision is released to correct the path. You should try `brew update` and `brew upgrade pipenv`, and if that doesn’t work, submit a bug report to Homebrew. There is nothing Pipenv can do here.

Side note: Personally I strongly discourage using Homebrew to install Python packages, or install any Python packages against the Homebrew Python using pip (or otherwise). It is just not a good idea.

**Comment by nathanielford** [comment]
@uranusjr I see! That makes a lot of sense; apologies for the noise. Thanks for the pointers!

**Comment by QQsha** [comment]
@nathanielford , did you fixed this problem with brew?

**Comment by wlbentley** [comment]
What method for managing installed python versions do you recommend (especially Mac OS)? Homebrew is not as flexible with this as I had hoped/imagined. Some projects do not yet support 3.7, which is the homebrew default at this time, so being able to easily specify a particular version is becoming a requirement for me. 

> Side note: Personally I strongly discourage using Homebrew to install Python packages, or install any Python packages against the Homebrew Python using pip (or otherwise). It is just not a good idea.

**Comment by nathanielford** [comment]
@QQsha I uninstalled pipenv from homebrew and installed it explicitly with `python3`.

**Comment by cs01** [comment]
@uranusjr have you tried pipx? It’s similar to pipsi but is actively developed.  It’s straightforward to install. https://packaging.python.org/guides/installing-stand-alone-command-line-tools/

pip install pipx —user
pipx install pipenv

**Comment by matteius** [comment]
Closing this issue as I believe the documentation is corrected these days, I just checked:

> It’s possible to install Pipenv with Homebrew on MacOS, or with Linuxbrew on Linux systems. However, this is now discouraged, because updates to the brewed Python distribution will break Pipenv, and perhaps all virtual environments managed by it. You’ll then need to re-install Pipenv at least. If you want to give it a try despite this warning, use:
