### ISSUE TITLE
pipenv lock -r create virtualenv at /root/.local/share/virtualenvs/. which was not expected.

### ISSUE THREAD

**Issue by hackrole** [pypa/pipenv#2336]
Please refer to our [StackOverflow tag](https://stackoverflow.com/questions/tagged/pipenv) for more information.
I use following command to build my dockerfile. I create virtualenv myself, cause I donot want a random-name virtualenv. but the pipenv lock seems create a virtualenv on somewhere, which was not expected.
```dockerfile
from python:3.6.5-slim
....
RUN pipenv lock -r > requirements.txt && /venv/bin/pip install -r requirements.txt
```
 it logs like following:
```logs
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m (3.6.5) to create virtualenv…
Running virtualenv with interpreter /usr/local/bin/python3.6m
Using base prefix '/usr/local'
New python executable in /root/.local/share/virtualenvs/server-Fk8nPUz7/bin/python3.6m
Also creating executable in /root/.local/share/virtualenvs/server-Fk8nPUz7/bin/python
```
how to not create a virtualenv while generate a requirements.txt.
and the `pipenv lock -r` run very slow, I have pipenv.lock in projects, but it seems not use it directly.

**Comment by erinxocon** [comment]
Hey @hackrole, thanks for using pipenv!  We use pipenv differently in our docker configs.  I recommend you check out our sample [dockerfile](https://github.com/pypa/pipenv/blob/master/Dockerfile).  A couple of things I would look at:

- Creating the requirements file before you create the docker and copying it into docker in your dockerfile.  When doing what you are currently doing in the dockerifle, pipenv has to invoke itself and creates a new environment.  If you want pipenv to use another virtual environment, it must be active before you invoke pipenv.  Pipenv will detect that it is running in a virtualenv and use it.
- Consider using the `--deploy` and `--system` flags of pipenv instead of creating a virtualenv.  When using a docker container, there really isn't the need to create a virtualenv since it's just one application. Installing things to the system python path in docker makes things easy.  

Is there a reason you have to install from your requirements file and not something like `pipenv install --dev --system --deploy`?

Cheers!

**Comment by techalchemy** [comment]
Locking requires isolated environments -- if you run `pipenv lock` it will always make a virtualenv.

**Comment by hackrole** [comment]
@erinxocon, It is just a habit. I will try to use things like``` --system --deploy```. Thanks for the answer
