### ISSUE TITLE
Add support for automatic setup.py creation

### ISSUE THREAD

**Issue by thealphadollar** [pypa/pipenv#2353]
**Is your feature request related to a problem? Please describe.**
It is always time-consuming to create a basic setup.py file to upload the package to PyPI. 

**Describe the solution you'd like**
Just as the `npm init` command, we can have an option to ask the user for basic information about the project and then create a setup.py file, with minimal attributes, ready to be used.

**Additional context**
https://docs.npmjs.com/cli/init

NOTE: I'm proficient enough to work on this if the idea is considered for implementation.

**Comment by uranusjr** [comment]
Hi! While I think this is a good idea, it is probably out of scope of Pipenv, since the project focuses on interacting with Pipfile and virtualenv. Feel free to create standalone tools for this task, however. [I have personally tried](https://github.com/uranusjr/pipub) to tackle this, but abandoned the effort due to lack of time (and since I don’t create setup.py that often anyway).

Thanks for the suggestion, and good luck!
