### ISSUE TITLE
"Loading .env environment variables" logs to stderr

### ISSUE THREAD

**Issue by caspervdw** [pypa/pipenv#2358]
This is a minor annoyance, as in some scripts we log stderr. 
I think this should be changed, as it is not an error message.

Thanks in advance!

https://github.com/pypa/pipenv/blob/4b95004f1aca99006a72789804a0d19cac95386c/pipenv/core.py#L166

**Comment by techalchemy** [comment]
Hey, thanks for the input! I agree it isn’t an error, but we actually log most things to stderr for various reasons. If we redo this it will be part of a broad restructuring, i would be very hesitant to change where we send messages haphazardly. Thanks again though!

**Comment by uranusjr** [comment]
Maybe it’d be reasonable to add an environ (`PIPENV_QUIET`) or something to suppress some of the informational messages we produce. This, the “installing initially failing packages”, the “ignoring marker”, and probably some else.

**Comment by techalchemy** [comment]
I think we have an env var and we just don't really use it much. We should flag this as a tracking item in a cleanup project

**Comment by foozmeat** [comment]
@techalchemy apologies for replying in a closed issue but I didn't want to open a dupe to add my thoughts.

I currently use `pipenv run` in several cron jobs and this creates a situation where I have to send all output to /dev/null or I get an email with `Loading .env environment variables…` on each run. I'm running the risk of not seeing real error output because I can't silence this message. I'd be all for a `-q quiet` flag or `PIPENV_QUIET` to handle this case.

Your last comment seems to indicate that you meant to re-open this. Maybe?

**Comment by uranusjr** [comment]
The `PIPENV_QUIET` has since been implemented, but it is not applied to `run` yet. Feel free to work on this.

**Comment by foozmeat** [comment]
@uranusjr I'm surprised to read that it has been implemented. As of version `2018.11.26` it doesn't appear in the list shown by `pipenv --envs` or listed in the docs.

I'll take a look at the code and try to implement it.

**Comment by thunderk** [comment]
I proposed a fix in #3457, if someone wants to reconsider this issue and review the PR. I think this issue is important for pipenv adoption, as properly using _pipenv run_ commands in cron may be a frequent use case.
