### ISSUE TITLE
pipenv destroy for destorying virtualenv's.

### ISSUE THREAD

**Issue by giuscri** [pypa/pipenv#2405]
**Is your feature request related to a problem? Please describe.**
It's not clear how to remove virtual environments from pipenv. I've found the `--rm` option (why an _option_?) in the issue tracker just before opening a feature request.

**Describe the solution you'd like**
Deprecate `--rm` option; `pipenv destroy` should be the preferred way for destroying virtualenv's.

**Comment by erinxocon** [comment]
Hi @giuscri!  Thanks for using pipenv!  I suspect the reason why it's an option is because we don't want to add hard commands to the api as it's not in the style, however @techalchemy could shed some more light.  The option is documented in the documentation here:  https://docs.pipenv.org/#cmdoption-pipenv-rm

**Comment by giuscri** [comment]
imho usage string should have an example using the `--rm` option

**Comment by uranusjr** [comment]
@giuscri contributions are welcomed :)

**Comment by giuscri** [comment]
See https://github.com/pypa/pipenv/pull/2597
