### ISSUE TITLE
Dependencies of local/VCS repositories are not locked

### ISSUE THREAD

**Issue by OrangeDog** [pypa/pipenv#2556]
Previously mentioned in #2180.

For this example, the directory `../test-dep` contains a setup.py:
```python
from setuptools import setup, find_packages

setup(
    name='test-package',
    install_requires=['python-dateutil']
)
```

```
$ pipenv install ../test-dep
[...]

$ pipenv lock --requirements
-i https://pypi.org/simple
./../test-dep

$ pipenv run pip freeze
python-dateutil==2.7.3
six==1.11.0
test-package==0.0.0
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/me/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-17134-Microsoft',
 'platform_system': 'Linux',
 'platform_version': '#112-Microsoft Thu Jun 07 22:57:00 PST 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LS_COLORS`
  - `HOSTTYPE`
  - `LESSCLOSE`
  - `LANG`
  - `SSH_AUTH_SOCK`
  - `S_COLORS`
  - `USER`
  - `PWD`
  - `HOME`
  - `SSH_AGENT_PID`
  - `NAME`
  - `XDG_DATA_DIRS`
  - `SHELL`
  - `TERM`
  - `SHLVL`
  - `LOGNAME`
  - `PATH`
  - `LESSOPEN`
  - `_`
  - `OLDPWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/me/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
  - `SHELL`: `/bin/bash`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/home/me/test`

---------------------------

Contents of `Pipfile` ('/home/me/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
test-package = {path = "./../test-dep"}

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/me/test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "5e069ae10feb99a01fd4a3a04279db1e89181f592abee0d9e0474cc559c7e7c9"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "test-package": {
            "path": "./../test-dep"
        }
    },
    "develop": {}
}

```
</details>

**Comment by techalchemy** [comment]
`pipenv install -e ../test-dep`

**Comment by OrangeDog** [comment]
But why should it have to be editable? That doesn't seem right.

I see you get the warning when installing (but not locking) a VCS dependency, but not a local one.
> Warning: You installed a VCS dependency in non-editable mode. This will work fine, but sub-dependencies will not be resolved by $ pipenv lock.
  To enable this sub-dependency functionality, specify that this dependency is editable.

However, when there are VCS sub-dependencies, it doesn't work:
```
$ PIP_PROCESS_DEPENDENCY_LINKS=1 pipenv install -e git+ssh://git@gist.github.com/a14f81ef84df0325d4072e81238c88d2.git#egg=test-dep-one
Installing -e git+ssh://git@gist.github.com/a14f81ef84df0325d4072e81238c88d2.git#egg=test-dep-one...
Obtaining test-dep-one from git+ssh://git@gist.github.com/a14f81ef84df0325d4072e81238c88d2.git#egg=test-dep-one
  Updating /home/me/.local/share/virtualenvs/test-8irq5sUh/src/test-dep-one clone
Collecting python-dateutil (from test-dep-one)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting test-dep-two (from test-dep-one)
  Cloning ssh://git@gist.github.com/1bfc42240657c69b1c04584637d78755.git to /tmp/pip-install-4slz0ozd/test-dep-two
Collecting six>=1.5 (from python-dateutil->test-dep-one)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pytz (from test-dep-two->test-dep-one)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Building wheels for collected packages: test-dep-two
  Running setup.py bdist_wheel for test-dep-two: started
  Running setup.py bdist_wheel for test-dep-two: finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-j98yqzz5/wheels/ca/94/0f/c68faa46c2db548327053dce81d58570e49f0ee40b6440583e
Successfully built test-dep-two
Installing collected packages: six, python-dateutil, pytz, test-dep-two, test-dep-one
  Running setup.py develop for test-dep-one
Successfully installed python-dateutil-2.7.3 pytz-2018.5 six-1.11.0 test-dep-one test-dep-two-1.0

Adding -e git+ssh://git@gist.github.com/a14f81ef84df0325d4072e81238c88d2.git#egg=test-dep-one to Pipfile's [packages]...
Pipfile.lock (b1c002) out of date, updating to (dc3125)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
 for candidate in matching_candidates
  File "/home/me/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 72, in get_hash
    hash_value = self._get_file_hash(location)
  File "/home/me/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 80, in _get_file_hash
    with open_local_or_remote_file(location, self.session) as fp:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/me/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 506, in open_local_or_remote_file
    response = session.get(url, headers=headers, stream=True)
  File "/home/me/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/download.py", line 398, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/me/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
pipenv.patched.notpip._vendor.requests.exceptions.InvalidSchema: No connection adapters were found for 'git+ssh://gist.github.com/1bfc42240657c69b1c04584637d78755.git'
```

**Comment by techalchemy** [comment]
1. There was a bug in the protocol implementation for this specific version of the vcs uri parser. 
2. It doesn’t have to seem right. It relates to the behavior of a dependency in editable mode vs non editable mode. At this point we could change that aspect of it but people rely on the distinction.

**Comment by OrangeDog** [comment]
> people rely on the distinction

What's the use case? Surely it should be the other way around - installing it as a normal dependency should behave like a normal dependency and lock properly, whereas if you make it editable it implies it's not in a fixed state so perhaps shouldn't be locked.

**Comment by techalchemy** [comment]
Sorry, this is a behavior that has been present since vcs dependency resolution was introduced and it is not going to be changed on a whim.

The use case is that sometimes people don't want their VCS dependencies locked. This behavior is consistent with other tools that predate pipenv but operate in the same space. It's not really up for discussion, if you want to learn more about the behavior please search the issue tracker. Explanations and re-explanations place high demands on our time and at the end of the day this decision _might_ be something we could technically change, but due to previous decisions it behaves this way and gives plenty of warning to that end

**Comment by OrangeDog** [comment]
Fair enough, but the goal of deterministic environments doesn't seem possible because of this decision, largely defeating the point of using pipenv in the first place. If people do want to not lock transitive sub-dependencies for some reason, that should really be a new per-dependency mechanism (e.g. `lock_transitive = false` in the Pipfile) independent of what kind of dependency it is.

> since vcs dependency resolution was introduced

Surely that was less than a month ago. VCS sub-dependencies weren't locked at all until the 2018.6.25 release.

> plenty of warning

That at least is not true. If you're installing local dependencies, or editing Pipfile manually, you get no warning at all.

**Comment by techalchemy** [comment]
Hyperbole makes me want to ignore your input. Determinist installation is completely possible. Sorry you don’t like passing an extra argument with your vcs delendencies. 

Sub dependencies and vcs locking were introduced a very, _very_ long tome ago. Just because you don’t know something doesn’t mean it’s not true. Please don’t come to the issue tracker and tell us what features existed and justify your demanding certain behavior based on those false impressions. You’re wrong, and the approach makes me see that you don’t read terminal output, documentation, past issues, and you aren’t considering other use cases besides whatever you happen to want right now this precise moment. 

You are dictating behavior using langauge like ‘should’, but says who? You just walk into random teams at work with no context and tell them how they should design and implement their products? You are making it clear you haven’t bothered yourself with reading any of the prior design discussions or issues on the topic, and seem to think only just worked out that we should include the transitive dependencies in the first place this past month. 

I’m not sure if this was your intention, but it certainly comes across quite condescending and I’m not really interested in dialogue if I have to continue explaining every decision and it gets met with ‘well what’s the point of even using this thing I’m using that you spend your volunteer time on and that I simultaneously also say never did this absolutely critical thing before a month ago.’  I don’t know, you have to answer this for yourself. Please do it off of the tracker.

**Comment by OrangeDog** [comment]
I'm not being hyperbolic. How is deterministically reproducing an environment possible if some of the dependencies are editable, thus subject to unpublished changes in different environments?

As previously pointed-out (which you are ignoring) you get no terminal output about this if you edit the Pipfile manually and update, which is what I was doing. Nor if you install a local dependency (as in my first example).

I have not read all 2555 past issues, no, that would be a ridiculous burden to place on someone asking a simple question. I did however, read #2180 where you told me you were working on making sub-dependencies of VCS dependencies lock (if they already did, why did you not correct me there?). The changelog in the documentation was then updated, indicating that this now worked, which is why I tested it.

This project looked like finally a route towards a good dependency management system for python, but if you're going to react this aggressively to every bit of input from the people you're supposedly trying to help (and who are trying to help you), then it's going to going to be yet another failure.

If there are previous discussions, link to them - you clearly seem to know where to find them. If things don't work how your users think, then your documentation needs improving. If people request features (like I did) and you implement them (like you did) don't yell at them when they give you some feedback on them. You say I'm not considering other's use-cases (but you won't tell me what they are), you are the one dismissing mine.

I'm sorry if my use of the word "should" offends you. If you prefer, replace it with "perhaps, in your infinite wisdom oh mighty pypa member, this might be behaviour that us lowly serfs might be lead to believe could possibly be a more correct course of action".

**Comment by techalchemy** [comment]
> I'm not being hyperbolic. How is deterministically reproducing an environment possible if some of the dependencies are editable,

Make them editable.  Calling it impossible is saying something is not possible.  When I just told you that it is possible, here is how to do it, and your reaction is 'it's not even possible', yeah, sorry, that's hyperbolic.  

> I have not read all 2555 past issues, no, that would be a ridiculous burden to place on someone asking a simple question. 

So it's a ridiculous burden to place  on you to use the search function, but not a ridiculous burden to place on _me_, who is already giving away my free work, time and effort, to also come to the issue tracker and demand that I also divert my attention to explain each detail of the decision that isn't to your liking, find and link each relevant issue, and justify why things aren't behaving as you wish them to.  Nope, the burden is on you.  You want something to be different, you think there is a bug? Step 1, you need to show the bug.  You want a behavior change? You want to come tell us how our software _should_ behave, but you can't be bothered searching through old issues on it? Guess you must not be that invested.

> This project looked like finally a route towards a good dependency management system for python, but if you're going to react this aggressively to every bit of input from the people you're supposedly trying to help (and who are trying to help you), then it's going to going to be yet another failure.

The project is doing fine. The sense of entitlement that comes with people thinking we need their help is a bit of a problem. 

> If there are previous discussions, link to them - you clearly seem to know where to find them. 

This is the height of entitlement.  You want to come here and demand stuff and not bother reading a single thing about why things work the way they do because it would be a "ridiculous burden" to ask of you to do a search in our issue tracker.  But you don't seem to find it much of a burden to come to our project and ask things of us, demand things of us, tell us how things need to work, etc.  So yeah, if you won't bother yourself to do a search, I'm not really interested to bother myself with your feature requests.

> If things don't work how your users think, then your documentation needs improving.

Contributions welcome. This is an open source project.  We merge improvements regularly.

> don't yell at them when they give you some feedback on them.

I'm not yelling at you for your feedback.  I'm expressing frustration at your entitlement and the hypocrisy of the fact that you want us to hand you a whole bunch of information and answer every request you make in detail without a second thought to the time it takes out of our day, but can't be taxed with the "ridiculous burden" of searching the issue tracker for previous discussions on the topic. This is not a productive way to engage with this or any project.

**Comment by OrangeDog** [comment]
You are not reading my comments properly, continuing to ignore when I have done exactly what you have demanded.

I know that if you make a dependency editable it will lock the sub dependencies, that was your first comment on this issue. The problem is that now I have an editable dependency, which is itself not deterministic, because it is able to be edited. That's what editable means. Indeed a ration person seeing a dependency set as editable would be expecting it to be edited, or there would be no need to set it as such.

I have searched previous issues for this. That's why I raised this on #2180 in the first place, because VCS sub-dependency locking was not covered. I have already pointed out the things you told me there and in the documentation, on which I have been basing my initial comments.

Yes, I think there is a bug (there are a couple here). I have demonstrated them. I have even been extra helpful and suggested some ways of solving these bugs. All I get from you is "I'm not discussing it" and walls of meta text.

Have you taken a second thought to consider the burden on me, who is also volunteering my free work, time and effort on this project? My frustration at your entitlement that everyone you speak to must already know everything you do? Your hypocrisy: "people thinking we need their help", "contributions welcome".

**Comment by techalchemy** [comment]
> Have you taken a second thought to consider the burden on me, who is also volunteering my free work, time and effort on this project? My frustration at your entitlement that everyone you speak to must already know everything you do? Your hypocrisy: "people thinking we need their help", "contributions welcome".

No.  Don't come to a project and tell me I'm entitled.  You're demanding stuff of us. That is literally the definition of entitlement.

**Comment by techalchemy** [comment]
For reference: https://www.youtube.com/watch?v=tzFWz5fiVKU&feature=youtu.be&t=48m55s

This forum is for our project; which is a thing that we created and distribute in our free time and which we manage voluntarily.  Comparing the time investment that we make to the burden of searching for related issues before demanding explanations of design decisions is a good way to get yourself on our bad side.

**Comment by uranusjr** [comment]
Some random thoughts on this one as a maintainer:

1. I don’t have an issue if the change is made to include dependencies of a VCS dependency. I would probably prefer that, in fact.
2. Making the change now would throw everyone relying on this off. Not a good idea unless we can provide an alternative.
3. This is like the venv in project vs centraised directory debate. I wish it were this other way around, and would most definitely fight for it if I were around when it was decided. But I was not, and the ship sailed. Too late to change that now.
4. Maybe, in the future, we can run a survey, put up a deprecation notice, and make the switch. I look forward to the day.
5. Alas, we are so far from that day. There are so many things broken, and so few people with so little time to fix them. 
6. This has a workaround, and is a design decision. We will visit it later.

It’s resource management at the end. I don’t think anyone would reasonably say this suggestion is an objectively wrong, but on the other hand, you can’t say the other behaviour is, either (you can claim one is _more_ correct than the other, but that is a different thing). With limited resource, however, we can only ask you to drop this. We can’t, and don’t want to deal with the consequences of the change.

I would like to mention that the pull request functionality is always open, and anyone is also free to comment on most issues to provide help and insights. Join us to help bring Pipenv to maturity, and then we will be able to revisit, and maybe correct mistakes we made along the way. Thank you.
