### ISSUE TITLE
Capture last install/synced Pipfile.lock hash in virtualenv to skip redundant installs/syncs

### ISSUE THREAD

**Issue by narfman0** [pypa/pipenv#2579]
I'm always frustrated when install/syncs take significant amounts of time when the lockfile hasn't changed. It'd be handy to have this handled automatically.

We can capture last installed/synced Pipfile.lock hash (meta/hash or similar) in virtualenv directory to skip redundant installs/syncs.

Command line parameters, redirecting to other files, and makefile/other infra changes are more time intensive workarounds that require pipenv introspection. Capturing hashes per venv would be a handy universal solution.

**Comment by erinxocon** [comment]
Hi @narfman0!  Thanks for using pipenv!  I'm wondering what version of pipenv you are using?  We added in a lot of caching features to help speed the process up.  I do not experience a slow down in sync/install unless I have to relock.  If you want to work on an example of how it could speed things up we welcome contributions!

**Comment by techalchemy** [comment]
Pipfiles are the source of truth for a pipenv managed virtualenv.  The minute your pipfile has changed, you need to re-resolve dependencies.

Hashes of the pipfile are already tracked, and we are tracking the overall performance concerns in a few other places, but it is not exactly straightforward to handle.  Just because the lockfile indicates that something was installed doesn't mean it actually _is_ installed, so whenever we run an installation we let pip confirm that the packages specified are actually installed.

**Comment by narfman0** [comment]
Thanks for the feedback! I made an example repo here: https://github.com/narfman0/pipenv-speed-test. 

My version is from osx, brew installed, `2018-7-1`. After everything was installed, rerunning the command took `0m12.391s`. Is this time is expected?

pipfile.lock itself is not a source of truth, but after pipenv is installed/syncd, we would know we are up to date. For a typical user, if the locks contents are the same next time we run the command, could we not at least add an argument to skip actually checking with pip if someone did something unexpected or nefarious?

Is this optimizing for users that dont follow pipenv conventions without giving those following a way around it? Perhaps an extra argument and warning, not impacting usage unless explicitly invoked. I might be able to provide a reference implementation.

**Comment by butla** [comment]
Hey, I'm think I'm bothered with the same issue. The first step in my `make test` target is `pipenv sync --dev`, so that the CI or the person who just cloned the repo can just run the tests without going through any setup steps. The problem is, even if I run `pipenv sync` a couple of times in a row, it always takes about 10 seconds for me.

Another issue for me is that in this case sync requires a connection to the Internet, which I don't always have when I'm moving around (and working).

I guess this could be mitigated by a fast comparison of, for example `pip freeze` and the versions in the lock file. Is there something fundamentally wrong about this assumption?

@erinxocon I guess this issue should be reopened. I'm using the newest pipenv - 2018.7.1

**Comment by uranusjr** [comment]
Run a `pip freeze` first sounds like a good workaround to me. This would however induce a overhead and would slow things down if you only have a few packages. Some benchmarking would be needed to determine whether this is worth it.

**Comment by butla** [comment]
For the case of a single dependency (just installed `port_for`), which is probably quite uncommon, pip sync takes ~1.0s. Pip freeze (running after `pipenv shell`) takes ~0,38s. Taking that 0,4 seconds where you expect it to run far longer when there are actually dependencies to install is probably not that big of a deal. But then again saving 9,6s when you don't need to do anything, which is often, sounds really nive.
