### ISSUE TITLE
pipenv --rm requires a Pipfile

### ISSUE THREAD

**Issue by dmtucker** [pypa/pipenv#2615]
I want to remove a virtualenv created by `pipenv`, but `pipenv --rm` says there isn't one unless a Pipfile is present.

##### Expected result

The virtualenv is found and removed.

##### Actual result

I get an error saying there is no virtualenv.

##### Steps to replicate

Setup:
```
dtucker@dtucker-wkstn:/tmp $ pipenv shell
Creating a virtualenv for this project...
Pipfile: /tmp/Pipfile
Using /usr/bin/python3 (3.5.3) to create virtualenv...
⠋Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/dtucker/.local/share/virtualenvs/tmp-XVr6zr33/bin/python3
Also creating executable in /home/dtucker/.local/share/virtualenvs/tmp-XVr6zr33/bin/python
Installing setuptools, pip, wheel...done.
Setting project for tmp-XVr6zr33 to /tmp

Virtualenv location: /home/dtucker/.local/share/virtualenvs/tmp-XVr6zr33
Creating a Pipfile for this project...
Launching subshell in virtual environment…
 . /home/dtucker/.local/share/virtualenvs/tmp-XVr6zr33/bin/activate
dtucker@dtucker-wkstn:/tmp $  . /home/dtucker/.local/share/virtualenvs/tmp-XVr6zr33/bin/activate
(tmp-XVr6zr33) dtucker@dtucker-wkstn:/tmp $ exit
```
Reproduce:
```
dtucker@dtucker-wkstn:/tmp $ rm Pipfile
dtucker@dtucker-wkstn:/tmp $ pipenv --rm
No virtualenv has been created for this project yet!
```
Workaround:
```
dtucker@dtucker-wkstn:/tmp $ touch Pipfile
dtucker@dtucker-wkstn:/tmp $ pipenv --rm
Removing virtualenv (/home/dtucker/.local/share/virtualenvs/tmp-XVr6zr33)...
dtucker@dtucker-wkstn:/tmp $ rm Pipfile
```

**Comment by rodxavier** [comment]
Did some investigation on this and I think the virtualenv is currently coupled with the Pipfile via the `virtualenv_exists()` method.

**Comment by techalchemy** [comment]
Pipenv only knows there is a project it is associated with because of the presence of a Pipfile. For more advanced virtualenv management, check out https://github.com/gtalarico/pipenv-pipes

**Comment by dmtucker** [comment]
Bummer... It would be nice if there was a way to get the convenience of `pipenv shell` without having to have a project or anything to clean up. Maybe something like `pipenv shell --no-project` could work?

I'm guessing the issue is that Pipenv may not be the only tool to create virtualenvs in `~/.local/share/virtualenvs/`? Seems like that wouldn't be an issue if, for example, `~/.local/share/pipenv/virtualenvs/` were used instead.

"Use a separate tool" doesn't seem much different than saying "just use `virtualenv` and `pip`"

**Comment by techalchemy** [comment]
@dmtucker running `pipenv shell` with no project would be the same as creating a virtualenv yourself. Many tools exist and handle this precise functionality; pipenv doesn't seek to be the end all be all of flexible virtual environment creation.  Quite the opposite in fact -- pipenv precisely attempts to reduce the number of options and decisions involved in creating a virtual environment _and managing its dependencies in the context of a project_.

Pipenv is designed to create reproducible environments.  If you want a throwaway virtualenv to activate and do random things with, but you don't want it to be stateful, and you don't want a project, consider that I am telling you this is not what pipenv is meant for and that you should be using another tool.  I don't really have an opinion about whether you should use virtualenv directly or virtualenvwrapper or some other helper (I use https://github.com/adambrenecki/virtualfish personally to manage this exact use case).  So yes, if you want to do things that are unrelated to pipenv, you should consider alternative options.

As for your guess at what the issue is surrounding this, or your resistance to installing additional tooling in the pipenv ecosystem, I'm not really sure how to answer that.  Pipenv isn't built for what you are trying to do.  This is not a bug and it's not a simple failure to consider where we are putting environments
