### ISSUE TITLE
Two patched safety's

### ISSUE THREAD

**Issue by hroncok** [pypa/pipenv#2677]
See https://github.com/pypa/pipenv/blob/master/pipenv/patched/safety.zip and https://github.com/pypa/pipenv/tree/master/pipenv/patched/safety

Is this intentional? Can the zip be removed?

**Comment by benhowes** [comment]
The zip is used in `core.py:do_check` (https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L2231), which I just found when looking for an issue which turned out to be in pyup. I've never seen a pattern like this, so I'd be really interested to see how this thread unfolds.

**Comment by sirosen** [comment]
@techalchemy added the non-zip version in [this commit](https://github.com/pypa/pipenv/commit/0df413c245974091df9d4edea2c5a5add6741518#diff-b26c1ec62cc1901bc0a6d41ee13126d0) and [he updated the zip version the next day](https://github.com/pypa/pipenv/commit/6e463c3cb0491a0f6bb75e3f15ea8182c2b47193#diff-5bd45603ad77e183abc4ed5bf0b21ca3).
So presumably he holds the answers? Nobody else has committed changes to the non-zip version (in fact, almost nobody else has touched either).

This seems weird though. If both are needed, a simple readme in the `pipenv/patched/` dir which explains this would be worthwhile.

**Comment by techalchemy** [comment]
@sirosen I doubt both are needed, but I was only recreating what kenneth had done (he created the zipped version but I believe we were bundling the entire safety database then);  I included the other one by accident most likely as a part of a commit at the time, I basically never touch it because the entire process of updating it was incredibly painful

I am mostly confident we can get rid of this but as with all things, time is a large driver of its continued presence
