### ISSUE TITLE
Feature: Default/universal dev dependencies for every venv

### ISSUE THREAD

**Issue by MADindustries** [pypa/pipenv#2715]
I would like to have a way to set default modules to be installed in every venv I create with pipenv. I regularly develop with pylint, yapf, rope, etc and I add them to every pipfile as a dev dependency. Is there or can there be a way to automate this?

I have considered making a generic pipfile with these dependencies and putting it into each directory before I run `pipenv install --dev` but this seems like more of a workaround than a real solution.

Thoughts? Am I completely using this tool wrong?

**Comment by uranusjr** [comment]
Not at all, you are doing it right. The explicit `--dev` flags is a design decision. The idea is that this prevents you from accidentally installing things you don’t want (e.g. in production) without noticing, while forgetting to supply `--dev` is more noticible because you’d see clear error messages when something is missing.

While the intention is good, I agree this is certainly not ergonomically optimal. A switch to flip the behaviour of _all_ projects on a machine sounds like the wrong solution to me, however. Maybe we should store this information somewhere in a per-environment basis, so if a project is initialised with `--dev`, subsequent `sync` would default to add `--dev` (suppressable with `--no-dev`). Or perhaps we can inspect the environment (like `pipenv clean` does), and put up a message like _hey this seems like a dev environment, maybe you want to supply `--dev`_?

Thanks for the suggestion! We will try to ponder on what the best design is, and figure out the implementation.

**Comment by matteius** [comment]
Category based package groups is likely going to suite the needs here as well:  https://github.com/pypa/pipenv/issues/4745
