### ISSUE TITLE
Add support to analyze code quality

### ISSUE THREAD

**Issue by wilfilho** [pypa/pipenv#2740]
Hi guys,

I was thinking in the possibility of add support to check code quality in _**pipenv**_. Integrating some tool like **flake8** or **pycodestyle** might be cool.

It could be something like:

`$ pipenv pep8`

Or could be inside command **_check_**. But anyway, it's something I'm interested in implementing. What do you think?

**Comment by uranusjr** [comment]
We did once provide flake8 support, but removed it in the end since *flake8 does not work well unless you install it in the virtual environment* (the same is true for pycodestyle). Pipenv by design works outside of the environment, resulting in inaccurate, or at worst wrong results when analysing the code.

I think the current resolution is keep ourself out of this problem, and let users install the tools “correctly”, i.e. inside the virtual environment, unless someone can provide a better approach to solve the problem.
