### ISSUE TITLE
Can't install autokeras 

### ISSUE THREAD

**Issue by paulgureghian** [pypa/pipenv#2854]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

If you're requesting a new feature or leaving feedback, please use this forum instead:

    https://kenneth-reitz.uservoice.com/forums/913660-general

Check the [diagnose documentation](https://docs.pipenv.org/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

##### Issue description

Describe the issue briefly here.

##### Expected result

Describe what you expected.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip
![capture15](https://user-images.githubusercontent.com/8146561/45570819-f2617800-b818-11e8-9883-74f5bb68a9ce.PNG)

**Comment by grahamlyons** [comment]
@paulgureghian, a lot of the information in the issue template is missing and I think it would be useful to have that. I know you can't go back to edit it so perhaps you could close this issue and re-raise it?

**Comment by techalchemy** [comment]
Based on the installation picture you provided, and I have to provide a guess because it's actually just a screenshot of a small segment of your failure logs, it seems like you are trying to install autokeras using python 3.7.

I don't use autokeras but I did google the installation instructions, and one of the first things they say is:

> Note: currently, Auto-Keras is only compatible with: Python 3.6.

I attempted to install auto-keras using python 3.6, but I saw that the latest autokeras has a strict pin on `keras==2.2.2`, which in turn pins `keras-applications==1.0.4` (I kind of question whether these types of incredibly strict pins are actually needed but I know basically nothing about the space so I can't say much).

However, the latest version of tensorflow is also installed (required: `>=1.10.0`, installed: `1.11.0`) and that requires `keras-applications>=1.0.5`, so I'd imagine with the strict pin on the rest of the stack they would also be pinning a core dependency like tensorflow.


I don't think `tensorflow 1.10` requires `keras-applications`, so you might be able to getg away with pinning that:

```toml
[packages]
autokeras = "*"
tensorflow = "==1.10.0"
```

Either way, there isn't much more we can do until we integrate a new resolver.  Sorry for the trouble, hope this helps!
