### ISSUE TITLE
pipenv --venv returns incorrect virtual env path

### ISSUE THREAD

**Issue by pdpark** [pypa/pipenv#2896]
##### Issue description

pipenv --venv 

Returns a path that is a concatenation of my actual virtual env with the location of the pyenv python version used when creating the env.

##### Expected result

Just the path to the virtual env:

/Users/<username>/.venvs/<pipenv-project-name>

##### Actual result

/Users/<username>/.venvs/<pipenv-project-name>/Users/<username>/.pyenv/shims/python

##### Steps to replicate

Environment created from existing requirements.txt using pipenv install --ignore-lock

From my .zshrc file:

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# pipenv
export WORKON_HOME=~/.venvs 
export PIPENV_PYTHON=$PYENV_ROOT/shims/python
eval "$(pipenv --completion)"

**Comment by techalchemy** [comment]
Hi, I'm going to go ahead and guess that you are using `pyenv-virtualenv` because I happen to know that it puts virtualenvs in your pyenv root directory.

You've described a few steps, but I really need you to _paste_ the output of _all of the commands_ required to replicate whatever you're seeing, including the output.  Simply describing this kind of problem isn't usually enough for us to really understand the issue, so if possible step by step instructions on exactly what to type in, with copy-pasted text of exactly what you saw as output, would be infinitely helpful in debugging this.

**Comment by techalchemy** [comment]
Hey there, we haven't heard back and we haven't heard any other reports of this, so I'm going to go ahead and close this for now.  Thanks for the report, and feel free to let us know if this comes up again in the new release
