### ISSUE TITLE
why

### ISSUE THREAD

**Issue by yiyinying** [pypa/pipenv#2904]
Can't find a usable init.tcl in the following directories

This probably means that Tcl wasn't installed properly.

**Comment by nateprewitt** [comment]
Hi @yiyinying, there isn't enough information here to provide a helpful response. The error you've provided is related to the TCL library not being installed or discoverable on your machine. That's a system level dependency that wouldn't usually be handled by pipenv.

I'm going to close this since the requested information wasn't provided and we don't have a path forward. Feel free to reopen when more you have more details. Thanks!
