### ISSUE TITLE
Some commands are not fully functional or don't work as expected

### ISSUE THREAD

**Issue by techalchemy** [pypa/pipenv#3126]
- Some pipenv commands are not fully operational or have known issues
- This is a meta-issue for tracking known issues

**Comment by oleksis** [comment]
I totally agree. I propose that you can send options to the pip subcommand from pipenv for example --timeout. In me it is almost important because with a slow connection to execute pipenv lock I get an error. I hope among all to find a solution. Regards!

Read More ... [ https://github.com/pypa/pipenv/issues/3122 ]
