### ISSUE TITLE
Support for repository json api?

### ISSUE THREAD

**Issue by zymergen-luke** [pypa/pipenv#3152]
### Is your feature request related to a problem? Please describe.

Pipenv dependency resolution is slow. While some of it is due to the recursive nature of discovering and invalidating dependencies, some it is is slow due to how Pipenv downloads packages and executes them to determine the dependencies. Pypi supports json endpoints that will deliver dependencies without the need to download/execute (though I don't believe it works for every package)

### Describe the solution you'd like

Pipenv appears to explicitly disable the newer api and use the legacy download/execute method, regardless of what the repo supports. (See pipenv/utils.py where it constructs PyPIRepository with `use_json=False`).

While this doesn't change the complexity of the algorithm, allowing use of the json api would greatly speed up the scalar factor.

### Describe alternatives you've considered

I'm mostly just looking for an update on your thinking about how dependencies are found and whether or not usage of the json api is on the horizon.

**Comment by uranusjr** [comment]
We consulted other PyPA members regarding this issue a while ago, and the advice we got was to avoid using the JSON API, unless we want to diverge from pip. pip does not use the JSON API, and there are edge cases that the Simple API yields different results from JSON. Since the Simple API is the only standard way of providing package information, those discrepancies can be considered as inaccuracies in the JSON API. The problem is, we don’t know exactly *what* is accurate, and *when*. This is an unfortunate situation, but there’s no way around it until someone takes on the task of vastly improving server-side infrastructure.

I am by no means very knowledgable of the server-side implementation, why this happens, and when. The mainling list [distutils-sig](https://mail.python.org/mm3/archives/list/distutils-sig@python.org/) would be a better place to find experts on this topic, and how the situation can be improved.
