### ISSUE TITLE
Minor: odd error text

### ISSUE THREAD

**Issue by dimaqq** [pypa/pipenv#3452]
```
> pipenv install --upgrade black
Installing --upgrade…
WARNING: Invalid requirement, parse error at "'--upgrad'"
✘ Installation Failed
```

So, how come it complains about `--upgrad` without the last character?

**Comment by jxltom** [comment]
Thanks for reporting the issue, it looks not right indeed.

**Comment by frostming** [comment]
`--upgrade` is not a valid options and `-e` is eaten by the parser.

**Comment by techalchemy** [comment]
could be like a click resilient parsing setting? it does seem odd

**Comment by frostming** [comment]
Reviewed this issue, this can be fixed by switching `ignore_unknown_options` to True.
https://github.com/pypa/pipenv/blob/28a902395b134ae6167a9207eb0214edbcbd39ea/pipenv/cli/command.py#L29-L32
Pipenv now owns all the command parsing, doesn't it? Maybe we don't need this flag anymore. 
/cc @techalchemy @uranusjr

**Comment by dimaqq** [comment]
The original error is gone, closing.

Same command now fails with `Installing --upgrade…` 🤷‍♂️
