### ISSUE TITLE
Should log more by default.

### ISSUE THREAD

**Issue by melMass** [pypa/pipenv#3482]
### problem

I'm always frustrated when I'm installing big libraries with pipenv on low networks.

### Describe the solution you'd like

I think by default `pipenv install` should log:
- Download progress 
- Locking progress

**Comment by techalchemy** [comment]
thanks for the issue -- this may be helpful, but please file separate issues with specific proposals about what you believe needs to be logged.  This is not really actionable and it's not possible to respond to this with a yes or no

**Comment by melMass** [comment]
What ?

**Comment by techalchemy** [comment]
Logging progress is not specific, we have a progress bar; the process isn’t divided into discrete steps of ‘download’ and ‘lock’ (separate thing entirely which requires a complete definition of what progress would even look like for it). Locking progress isn’t really meaningful either because of the nature of dependency resolution. 

`install` spins off up to like 15 subprocesses which report when they run but can’t do much more than that since subprocesses can’t really report up to the main progress bar cleanly, and again there is no ‘download’ step. Sometimes there is no download at all. Your proposal is vaguely to log some progress for download and locking. This is complicated and the request is not specific enough to be sure what exactly you want, so issues for each behavior describing what specific information you’d like to see and when would be far more helpful.
