### ISSUE TITLE
Support for environment variables in requirement specifiers

### ISSUE THREAD

**Issue by gioele** [pypa/pipenv#3516]
Pipenv should accept bash-like enviroment variables in requirement specifiers and substitute them on the fly when pipev is run.

### Is your feature request related to a problem? Please describe.

One possible use of this feature is installing packages from private GitHub repositories  via OAuth. Right now this is not possible without storing the OAuth token in plain text in `Pipenv` like, for example:

```ini
[packages]
private-package = {editable = true,
    git = "https://1234abcdef56789:x-oauth-basic@github.com/myorg/private-package.git",
    ref = "v2.1"}
```

### Describe the solution you'd like

It would be nice if bash-like enviroment variables where accepted and substituted on the fly when pipenv is run. For example:

```bash
pipenv install 'git+https://${GIT_TOKEN}:x-oauth-basic@github.com/myorg/private-package.git@v2.1#egg=private-package'
```

(Please note the single quotes.)

### Describe alternatives you've considered

In plain pip it is possible to use `pip install -r <(envsubst < requirements.txt)`. This solution, however, is not possible with pipenv.

### Additional context

See also pypa/pip#6244.

**Comment by slavaatsig** [comment]
Yes! Yes! Please!
I was about to open this issue but found that it’s already created!
For an example for Google App Engine projects that are relying on private repositories, I can use my OS environment variables to safely install dependencies in a local environment and deploy to GAE using `pip` but cannot do the same using Pipenv without hard-coding credentials in the Pipfile.

**Comment by slavaatsig** [comment]
Also, I believe that [PEEP-002](https://github.com/pypa/pipenv/blob/master/peeps/PEEP-002.md) should be updated accordingly. Implementation of this feature really helps from security point of view.

In order to keep using Pipenv but avoiding to specify credentials in `Pipfile` (that is tracked in the VCS), I have implemented some scripts in Pipfile that are replacing custom placeholders with content from environment variables before installation and then do the opposite upon installation.

> Describe alternatives you've considered

_Having pip-like support of the environment variables in `Pipfile` would be much beter than these akward wheel on a cratched work-arounds._

**Comment by manskx** [comment]
Yes Please !

**Comment by uhurusurfa** [comment]
Happy to help implement of there is buy in to provide a solution.... need this

**Comment by skyoo2003** [comment]
I add a comment because I thought this problem was not being handled.

Pip supports installation by passing the environment variables to the VCS URL, but it seems strange that Pipenv does not support them. ( https://pip.pypa.io/en/stable/reference/pip_install/#id10 )

I am just waiting for this issue to be resolved. Please!

**Comment by roger-domenech-aguilera** [comment]
It will be very helpful. Thanks!
