### ISSUE TITLE
Pipfile.lock and dev transitive dependencies

### ISSUE THREAD

**Issue by belm0** [pypa/pipenv#3550]
### Issue description

Pipfile.lock "development" section seems appears to include transitive dependencies which are redundant, yet often have different versions than "default" dependencies.

I've confirmed that these redundant dependencies are not needed.  (E.g. if a package is only listed as dependency in "default' of Pipfile.lock, and you do a `pipenv sync --dev`, it will get installed.)

### Expected result

Given that `--dev` implies default + dev dependencies, I don't expect there to be dependencies duplicated between the default and dev sections of Pipfile.lock.  Moreover it's confusing to see contradicting versions specified for the same package within the Pipfile.lock.

### Actual result

"development" section of Pipfile.lock contains transitive dependencies which are redundant and often different than "default' section.

**Comment by techalchemy** [comment]
Yes, yet the sections are different and they therefore contain different content.  This is because you can specify different requirements in each section and they are resolved separately, and in theory (although due to an implementation detail, not in practice just yet), they can be manipulated separately.

In reality this functionality has been built out but the desired behaviors are not well defined.  The former constraints were around merging the sections together during installation, so we always prioritize any appearance of a package in `packages` as opposed to `dev-packages`.  This is a lossy approach as extras are dropped during this process (among other things).  In a future release we will be able to merge this information properly so that extras specified in the `dev` section are appropriately merged into any extras from the main section, etc.

So, while the metadata underlying the transitive dependencies may on occasion be overridden or ignored, that definitely does not mean the section is not necessary.  If you were to read the code underlying the implementation and propose an approach via a `PEEP` (pipenv enhancement proposal) to alter the way we are handling dependency resolution, explaining how we can remove our implementation and why you feel it is not necessary, I am guessing we would review it.  The current implementation is not an accident however so you would have to address the reasons behind its design and an alternative way to do the things we are planning to do with it.

As this issue is kind of a more general comment about the current situation being somewhat unclear/unfortunate, I'm going to close it for now.  As an FYI I'd be happy to review/comment on/work through a PEEP that just outlines the existing plan if that helps -- time is the biggest constraint on our end which is why none of this is documented clearly

thanks for the issue and hopefully this at least somewhat clarifies things
