### ISSUE TITLE
Allow command line arguments to have project local persisted defaults

### ISSUE THREAD

**Issue by thomasf** [pypa/pipenv#3707]
(This is a follow up issue to #3700 with an expanded problem description and alternative solution.)

### background

When working in many projects with lots of other people I have seen that I have to who might not know or understand the implications of all the details of how pipenv works,  some people are just programmers and should not have to be bothered by these details.

Pipenv is a fairly complicated tool and for most non maintainer developers of a project being able to set these values in the project repository would be very good from a developer experience perspective.

### setting default project local persistent values 

I would as an example like that `pipenv install` were always by default running with `--keep-outdated` and  maybe `--selective-upgrade` unless otherwise specified in a lot of projects.  

### using environment variables

Since the two settings I mentioned (and some other) can be set by environment variables environment variables can be used. However, I see two very significant problems with environment variables:

1. They do not propagate automatically to every developer of a project/repository which is the whole point of this change proposal. 
2. For a lot of windows developers environment variables are not obvious features at all. (I've spent a considerate amount time over my career helping windows developers set up and understand environment variables in various contexts even though I'm not a Windows user myself)

### possible solution

I suggest that pipenv starts trying to read a tool specific env file like `pipenv.env` before reading the plain `.env` in the same directory as the Pipfile.
This would allow defaults to be specified in `pipenv.env` and checked in into the repository while  `.env` still can be used for local settings override.

**Comment by techalchemy** [comment]
As a general comment I think I personally would lean towards putting things in `pyproject.toml` at this point -- everyone else seems to do that

On the `--keep-outdated` point I think `--keep-outdated` is too polluted of a command right now and is super confused.  The naming of it and the behavior of it performs kind of a split function and that needs to be clarified in some real way -- it partly attempts to make a minimum viable change to your lockfile, but _only_ if you are introducing new packages.  On the other hand it tries to make sure not to drop any dependencies that may have been lost due to mismatched environment markers.

Because of that confusion it has a super limited window of utility, but is incredibly useful for that.  `pipenv install --selective-upgrade` is the actual useful command because it lets you upgrade / install only the minimum required set of packages given a specific requirement.

The missing command is one that will re-lock to the current versions across the board but retain anything with environment markers that would otherwise drop out. That specific point makes me want to break the command apart before doing anything in the way of recommending that people use it

Overall I'd definitely be interested in a PEEP on the topic because I think you're spot on, and once the behavior is defined I don't think it would be that hard to work out
