### ISSUE TITLE
How to forward important arguments to pip?

### ISSUE THREAD

**Issue by npielawski** [pypa/pipenv#3734]
Hello!

I am trying to use the library [APEX](https://github.com/nvidia/apex), and I would like add --cuda_ext --cpp_ext to pip in order to install the library properly.

Is it possible to do this with pipenv? I already checked #251 and #287.

Have a nice day,
Nicolas

**Comment by uranusjr** [comment]
How do you pass that to pip? I don’t think you can just do `pip install --cud’s_ext` 🤔

**Comment by npielawski** [comment]
Technically, I'd like to do something along the lines:
`pipenv install git+https://github.com/nvidia/apex.git --cuda_ext --cpp_ext`
So that under the hood, the following command is called:
`pip install . --cuda_ext --cpp_ext`

**Comment by techalchemy** [comment]
You may be looking for the [--global-option](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-global-option) argument to pip. Per [the documentation in the repository you linked](https://github.com/nvidia/apex), the actual pip install command would be:

```console
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```

In order to achieve this with pipenv you simply need to set the environment variable `PIP_GLOBAL_OPTION="--cpp_ext --cuda_ext"` and it will be passed to pip (I think).  Feel free to reopen this if it fails.
