### ISSUE TITLE
"Pipenv install" appears to hang when pip configured to prompt for password

### ISSUE THREAD

**Issue by chrish42** [pypa/pipenv#3770]
In some cases, `pip` can prompt for a password when setup with an alternate package registry. When that happens, `pipenv install` appears to hang: pip is waiting for the user to enter the password, but there's no sign of that on the terminal because `pipenv` captures `pip`'s output.

Setting stdin to /dev/null (instead of PIPE) would at least cause `pip` to exit and then `pipenv` would show an error to the user, which would lead to faster diagnosis of the problem, and would not harm anything when `pip` doesn't need user input. I can submit a pull request if this change is ok. Thanks!

**Comment by abusque** [comment]
I also think that the current default behaviour is less than ideal, but I'd like to point out that it can be worked around by the end user by setting the environment variable `PIP_NO_INPUT=1`, which will cause pip (and subsequently pipenv) to exit when credentials are missing, rather than trying to prompt the user for input.

**Comment by frostming** [comment]
A workaround is to set env var `PIPENV_NOSPIN=1`.

Close it now.
