### ISSUE TITLE
Please make clear that `.cache/pipenv/` is created when initialising pipenv.

### ISSUE THREAD

**Issue by SebastianoF** [pypa/pipenv#3803]
One of the reasons why virtualenvs are so valuable is that everything related to the created env is contained in the single specified folder. There are no silently created folder outside of it.

Is it possible to specify that the auxiliary folder `.cache/pipenv/` is created each time a new pipenv is created?

Thanks

**Comment by techalchemy** [comment]
Like `pip`, `pipenv` creates a cache for the things it downloads.  This is a standard practice and creating it inside the virtualenv itself would defeat the purpose.  The cache is global because it allows global sharing of previously downloaded artifacts.

I am not aware of other software that alerts you to its creation of appdirs such as `~/.cache` subdirectories.  Pipenv works fine without this and doesn't claim to never create anything outside the virtualenv.  If there was some problem this caused for you that you'd like addressed I'd invite you to open another issue on that subject, but I am going to close this one for now since we already display a substantial amount of text upon environment creation

Thanks for the report
