### ISSUE TITLE
Switch to a dedicated tool for Pipenv’s own vendoring process

### ISSUE THREAD

**Issue by uranusjr** [pypa/pipenv#4075]
pip recently moved their vendoring tasks to a separate project (pypa/pip#7485). We might want to reuse that since Pipenv’s vendoring tasks are largely modelled after pip.

cc @pradyunsg @techalchemy

**Comment by pradyunsg** [comment]
Yeah, I'll file a PR for this soon-ish.

First though, I need to improve the messaging based on the latest comment by @dstufft to discourage use by folks who don't *definitely* need it (basically everyone except pip and similar tools), since we don't want to make life harder for redistributors who don't like vendored packages.

**Comment by techalchemy** [comment]
Since I’m on both sides of this issue now as a maintainer and a redistributor I’m in favor. Just wrapping up vendored updates hopefully so we can cut a release. I believe I can start handing out access as well. Then I am pretty fine with any changes.
