### ISSUE TITLE
Pipenv prefers a local package with the same name

### ISSUE THREAD

**Issue by andreif** [pypa/pipenv#4120]
### Issue description

I have a subfolder with name "requests" that contains an empty "setup.py". I try to import the real requests package from PyPI by running `pipenv install requests`

### Expected result

I expect the real requests to be installed.

### Actual result

Pipenv tries to install the local requests package. Pipenv should install local packages if I provide a path to it, not just the name, e.g. `pipenv install ./requests`.

### Steps to replicate

```sh
mkdir requests
touch requests/setup.py
pipenv install requests
```

**Comment by uranusjr** [comment]
This has been identified as a bug in pip, and will be fixed (pypa/pip#7955) by the next pip release scheduled later this month. I will close this for now since the diagnose (if correct) puts the solution out of Pipenv’s reach. Feel free to reopen if this still happens with pip 20.1 (i.e. indicates the diagnose was wrong).
