### ISSUE TITLE
Alternatives to Pipenv?

### ISSUE THREAD

**Issue by lucidyan** [pypa/pipenv#4143]
For those looking for alternatives to migrating from Pipenv, I found several options:

[Official recommendations from Pypa](https://packaging.python.org/guides/tool-recommendations/#application-dependency-management):
| Package  | Stars |
| ------------- | ------------- |
| https://github.com/python-poetry/poetry  | 9400  |
| https://github.com/pypa/pip     | 6100  |
| https://github.com/jazzband/pip-tools      | 4000  |

Others:
| Package  | Stars |
| ------------- | ------------- |
| https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md     | 4700  |
| https://github.com/dephell/dephell     | 1100  |
| https://github.com/David-OConnor/pyflow     | 365  |

Any other suggestions?

**Comment by lucidyan** [comment]
All information is taken from https://github.com/pypa/pipenv/issues/4058

**Comment by erinxocon** [comment]
I will say that I use this project every day still.  I know there are bugs with it but the team is small.  Pipenv aims to replace the need to invoke pip, virtualenv, and pip-tools directly by wrapping them but we completely rely on them for underlying functionality.  Pipenv gives me the ability to deploy my web applications in a deterministic environment, instead of requirements.txt you get a lock file that is secure and again deterministic.   If I'm doing library development I would likely use poetry or flit so I can abide by PEP 517 and PEP 518 and use pyproject.toml to config my build system, none of which pipenv does or tries to do.  In essence use the tool that works for you, but know that they all do have kind of specific use cases.

**Comment by jessekrubin** [comment]
Highly recommend using poetry and/or dephell and/or pip-tools. 

Also highly recommend using not pipenv, except when you’re craving a headache/migraine. 

Pipenv could/should be super dope, but in my experience it does not make life easier.

**Comment by hackf5** [comment]
> Highly recommend using poetry and/or dephell and/or pip-tools.
> 
> Also highly recommend using not pipenv, except when you’re craving a headache/migraine.
> 
> Pipenv could/should be super dope, but in my experience it does not make life easier.

You seem to be right. The inability to set a minimum python version in pipenv is a significant annoyance.
