### ISSUE TITLE
pipenv.core.which: allow_global has little to no effect

### ISSUE THREAD

**Issue by CyberDomovoy** [pypa/pipenv#4163]
https://github.com/pypa/pipenv/blob/a883ef515933e7f4dba16c6e4341dbdb11db1c04/pipenv/core.py#L109

This line causes a system search even when `allow_global != True`

More: what is `p` on this line when `allow_global != True and is_python != True`?
imho from https://github.com/pypa/pipenv/blob/a883ef515933e7f4dba16c6e4341dbdb11db1c04/pipenv/core.py#L101 we should have something like:
```python
    if not allow_global:
        if os.name == "nt":
            p = find_windows_executable(os.path.join(location, "Scripts"), command)
        else:
            p = os.path.join(location, "bin", command)
    else:
        if is_python:
            if os.path.exists(sys.executable):
                p = sys.executable
            else:
                p = system_which("python")
        else:
            p = system_which(command)
    
    # We should also check if it is executable, but that's another issue
    if not os.path.exists(p):
        p = None

    return p
```

**Comment by techalchemy** [comment]
Yes I generally agree that this functionality is terrible; I am reluctant to make any changes here without extensively testing, however, as this code has caused many historical issues for users.

So if I understand correctly you are proposing the following changes:


```diff
     else:
         if is_python:
+            if os.path.exists(sys.executable):
+                p = sys.executable
+            else:
+                p = system_which("python")
-            p = sys.executable
-    if not os.path.exists(p):
-        if is_python:
-            p = sys.executable or system_which("python")
         else:
             p = system_which(command)
 
+    # We should also check if it is executable, but that's another issue
+    if not os.path.exists(p):
+        p = None
+
     return p
```

What I see here is an additional `sys.executable` lookup to check if the path exists *before* assigning it to a variable, as compared with the more optimized assignment-first approach before checking for existence. Beyond that, the functionality is basically identical except for the comment about checking whether the file is executable, which would require jumping through a lot of hoops to achieve on windows, so it's not really practical for our purposes.

Since this basically is working (and too fragile to change without good reason), I'm going to close this issue out -- thanks for digging into the code and proposing changes, I appreciate the help!
