### ISSUE TITLE
pipenv lock: hangs when internet is slow. So is it ok to skip pipenv lock and do it once in a while when we have good internet speed

### ISSUE THREAD

**Issue by sant527** [pypa/pipenv#4260]
Recently i observed that `pipenv lock` gets hanged.

I have read about the issue at many places

But practically i found on my pc that when its connected to `slow internet speed (200-700 kbps)` it `stucks` and when it is connected to `good internet speed (2-3 Mbps)` it `works fine`

Also i found that whenever ever i do `pipenv lock` it downloads `200-300 Mb` data. Thats fine but just to know

So what i want to do is whenever i install a new package i want to skip the `pipfile.lock` getting updated using `--skip-lock` option

     i.e pipenv install --skip-lock somepackage

Later when i am connected to good internet speed i can do 

    pipenv lock

    Locking [dev-packages] dependencies…
    ✔ Success! 
    Locking [packages] dependencies…
    ✔ Success! 

I am just curious will this have any drawback in terms of identifying the versions installed at the time of installation

**Comment by benatkin** [comment]
This properly describes the issue here: #3827 

It's much slower than just the speed it would take to download the amount of data that ends up getting downloaded, because there is a lot of back and forth to install the packages.

It's like SQL where you have 50 queries due to an N+1 query issue. If you're close to the database, it might not be noticeably slow, but once you're far away from the database, it's sloooooow.

**Comment by januszm** [comment]
I generated a flamegraph of what happens inside the `main` function of the resolver.py, see: https://github.com/pypa/pipenv/issues/3827#issuecomment-784446651
on a poor internet connection pipenv install's bottleneck is downloading stuff

**Comment by matteius** [comment]
I think the answer to the OP is yes it should be fine to do this when your internet connection is having slowness.
