### ISSUE TITLE
Command line completion takes almost a second

### ISSUE THREAD

**Issue by marlonrichert** [pypa/pipenv#4367]
### Issue description

On the command line, when I type `pipenv ` and then press <kbd>Tab</kbd>, it takes almost a second for completions to show. This is very slow in comparison to other completions I use.

### Expected result

I expect completions to be shown in about one tenth of a second.

### Actual result

It takes about 0.75 seconds.

### Steps to replicate
Run this a couple of times in Zsh (or the equivalent in another shell):
```shell
typeset -F SECONDS=0; env COMMANDLINE="pipenv" _PIPENV_COMPLETE=complete-zsh pipenv > /dev/null; echo $SECONDS
typeset -F SECONDS=0; env COMMANDLINE="pipenv -" _PIPENV_COMPLETE=complete-zsh pipenv > /dev/null; echo $SECONDS
typeset -F SECONDS=0; env COMMANDLINE="pipenv install --" _PIPENV_COMPLETE=complete-zsh pipenv > /dev/null; echo $SECONDS
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'/usr/local/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2020.6.2/libexec/bin/python3.8'`

Python installations found:

  - `3.8.2`: `/Users/marlon/.pyenv/versions/3.8.2/bin/python3`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT '
                     '2020; root:xnu-6153.121.2~2/RELEASE_X86_64',
 'python_full_version': '3.8.3',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `MANPATH`
  - `LESS_TERMCAP_mb`
  - `TERM_PROGRAM`
  - `LESS_TERMCAP_md`
  - `PYENV_ROOT`
  - `LESS_TERMCAP_me`
  - `HELPDIR`
  - `TERM`
  - `SHELL`
  - `HOMEBREW_REPOSITORY`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `ZPFX`
  - `LESS_TERMCAP_ue`
  - `TERM_SESSION_ID`
  - `PMSPEC`
  - `USER`
  - `LS_COLORS`
  - `SSH_AUTH_SOCK`
  - `PAGER`
  - `LESS_TERMCAP_us`
  - `AUTOSWITCH_VERSION`
  - `_`
  - `WORDCHARS`
  - `PWD`
  - `P9K_SSH`
  - `EDITOR`
  - `P9K_TTY`
  - `LANG`
  - `XPC_FLAGS`
  - `ZLE_REMOVE_SUFFIX_CHARS`
  - `AUTOSWITCH_FILE`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `HOMEBREW_PREFIX`
  - `ZSH_CACHE_DIR`
  - `LESS`
  - `LOGNAME`
  - `VISUAL`
  - `LC_CTYPE`
  - `LESS_TERMCAP_so`
  - `FZF_DEFAULT_COMMAND`
  - `INFOPATH`
  - `HOMEBREW_CELLAR`
  - `DISPLAY`
  - `LESS_TERMCAP_se`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2020.6.2/libexec/tools:/Users/marlon/.pyenv/bin:/Users/marlon/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/Users/marlon/Applications/apache-tomcat-8.5.55/bin:/usr/local/opt/ncurses/bin:/Users/marlon/.zinit/polaris/sbin:/Users/marlon/.zinit/polaris/bin:/Users/marlon/.zinit/polaris/usr/sbin:/Users/marlon/.zinit/polaris/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:.`
  - `SHELL`: `/usr/local/bin/zsh`
  - `EDITOR`: `nano`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/var/folders/24/37_vm48s2tz9bhmj1rzffvl40000gn/T/tmp.J1AQqvjP`

---------------------------

</details>

**Comment by frostming** [comment]
Pipenv completion is backed by `click-completion`, which uses a dynamic means to decide the word to complete. With that said, Pipenv will have to be launched for every time you hit <kbd>TAB</kbd> to complete.

That is totally an issue of technical choice.

**Comment by Bananaman** [comment]
Another issue is that the suggested way of adding the autocompletion (in the readme) is very, very slow and adds at least half a second to your shell startup time, since it has to wait for Python and pipenv to initialize on every shell startup.

There's a much better way to do the autocompletion setup.

## Step 1. Write the autocompletion code to a file or your shell init script.
## Step 2. Load the autocompletion code into your shell init script.

## Example:

I decided to write it directly into the shell init scripts because I don't want to deal with figuring out a place to put the external file. This is what that looks like. I use both ZSH and Bash on my system:

```sh
echo '# Add pipenv autocompletion' >> ~/.zshrc
_PIPENV_COMPLETE=zsh_source pipenv >> ~/.zshrc

echo '# Add pipenv autocompletion' >> ~/.bashrc
_PIPENV_COMPLETE=bash_source pipenv >> ~/.bashrc
```

Run this ONCE. Never again. The code it adds to your shell init scripts is generic and simply says "when user presses tab to autocomplete a pipenv command, grab the result via pipenv". If pipenv ever refactors the autocompletion to use other environment variables, the autocompletion would break and you would have to refresh this code. But that will most likely never happen.
