### ISSUE TITLE
My issues with this pipenv

### ISSUE THREAD

**Issue by denohpakni** [pypa/pipenv#4415]
### Issue description

* takes too long to process
* doesnt remember to code input history
* doesnt install other dependencies, just the specific package

### Expected result

1. It needs to be faster
2. Remeber my code history
3. Install other dependencies, like installing pylint also installs six, toml etc

**Comment by mjpieters** [comment]
> 1. It needs to be faster

Recent versions have a major performance regression, see #4403 

> 2. Remember my code history

Pipenv is a command-line tool, not a shell, it has no command history. That's what your shell is for. If that is not what you meant then you need to clarify what this is meant to convey.

> 3. Install other dependencies, like installing pylint also installs six, toml etc

What makes you think it *doesn't* do this?

`pipenv install pylint` adds `pylint` to your top-level dependencies in `Pipfile`, *and* installs `pylint` into the virtualenv. This includes all dependencies! (It wouldn't work otherwise). The dependencies (which can change from release to release!) are tracked in the lock file, `Pipfile.lock`.

Try running `pipenv graph` to see the dependency tree for your projects.
