### ISSUE TITLE
Pipenv fails to install package that is installable with pip

### ISSUE THREAD

**Issue by jtiai** [pypa/pipenv#4440]
### Issue description

Pipenv has different concept of latest package than pip

When trying to install Ursina game engine it does have unpinned dependency panda3d. When running pipenv install panda3d in 
windows pipenv triest to use latest in pypi, version 1.10.6.post2. This package doesn't though have wheels for windows and installation fails.

Pip OTOH installs "latest installable" and picks 1.10.6 version which does have windows wheels available.

### Expected result

Functionality would match pip functionality to be able to install packages same way as with pip.

### Actual result

Installation fails due picking wrong package version.

### Steps to replicate

Running the following command fails:
```
pipenv install panda3d
```

-------------------------------------------------------------------------------

**Comment by frostming** [comment]
Pipenv lock file is designed to be cross-platform. So at the point of locking Pipenv doesn't know which platform it is going to be installed and has to pin the **latest** version available, since it doesn't support different version entries for the same package.

However, you can easily work around this by putting the following in your Pipfile:

```toml
pandas3d = {version="==1.10.6", sys_platform="=='win32'"}
```
