### ISSUE TITLE
Autocomplete capability on Windows

### ISSUE THREAD

**Issue by eddie-LA** [pypa/pipenv#4561]
Hello,

I searched a lot about this but only managed to find solutions for Linux shell autocomplete. I am using conda and it has the ability to Tab-autocomplete but the moment I have to use pipenv and I do `pipenv shell` - no autocomplete. It can be annoying to get used to having that Tab-autocomplete and then suddenly to not have it when you need to do rapid testing... 
Is there a way to work around this, is this a bug or does it not exist currently...? If it doesn't I will turn this into a feature request.

Thank you and kind regards.

**Comment by totallyzen** [comment]
Hi, not a pipenv-dev here but I think this may be more relevant to your choice of shell instead of `pipenv` itself. Despite that you can opt to turn it into a full feature request - but I think you'll get faster results if you consider the WSL in Windows or CygWin or the shell program you get when you install `git`.

**Comment by oz123** [comment]
Hi, which shell are you using in windows? Currently, there is completion for UNIX shells only.

**Comment by matteius** [comment]
Requires bash support, I think a good shell for windows is git for window:  https://gitforwindows.org/
