### ISSUE TITLE
Pipenv locking takes forever and never finishes

### ISSUE THREAD

**Issue by kareemamrr** [pypa/pipenv#4587]
### Issue description

`pipenv lock` never finishes even after 30 minutes.
Tried downgrading to `2018.11.26` as others suggested but no dice.

### Steps to replicate

Command: `pipenv install`
Pipfile:
```bash
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
natsort = ">=7.0.1"
librosa = ">=0.7.2"
dill = ">=0.3.1.1"
python-speech-features = ">=0.6"
tqdm = ">=4.45.0"
click = ">=7.1.1"
pandas = ">=1.0.3"
matplotlib = ">=3.2.1"
tensorflow = ">=2.3.0"
keras = ">=2.3.1"
numpy = ">=1.18.2"
numba = ">=0.48"

[dev-packages]

[requires]
python_version = "3.8"
```

**Comment by kareemamrr** [comment]
Update. After letting it go on for over an hour, this is the [output](https://gist.github.com/kareemamrr/c041da0ac52fe6b734e743d4f0ab303b)

**Comment by fridex** [comment]
You can try to use [this lock file](https://gist.github.com/fridex/97300628d27b9ae098d9ce91cdf6a44c).

**Comment by januszm** [comment]
Probably someone else has written about it before but ... wouldn't it be easier to replace pipenv's `resolver.py` with one that was added to `pip` some time ago? It's definitely better to focus and consolidate efforts on one good project instead of having people developing resolvers separately in pip, pipenv and poetry.

**Comment by cclauss** [comment]
Similar to #4430
