### ISSUE TITLE
Pipfile "exclude"/"excludes" dependency feature syntax

### ISSUE THREAD

**Issue by dashsatish** [pypa/pipenv#4648]
Hi,
Is there a way one can exclude a dependency using pipfile syntax.

OS: macOS Catalina 10.15.6
python: 3.8.8
pip: 21.0.1
pipenv: 2018.11.26

For example: 
    I need all the dependencies of `fastapi` except `orjson`
    
    Tried out:
     1)
     [packages]
     fastapi = {extras = ["all"], version = "*", excludes=["orjson"]}
     2)
      mentioning it in the excludes section if such a syntax is supported
      [packages]
      fastapi = {extras = ["all"], version = "*"}
      [excludes]
      orjson = "*"

Conclusion:
None of the above seem to work. I still see `pip freeze` listing out orjson as an installed lib. 
Any help will be greatly appreciated.

**Comment by frostming** [comment]
Why did you want to exclude some deps when they are defined explicitly in the project's metadata? You know, they must exist for some reasons.

**Comment by josh-hernandez-exe** [comment]
some project list a dependency that isn't pip installable. Like some jupyter kernel project list the foreign language version in the dependency.

So would need to be installed before (or independent) `pipenv install`. (a specific example would be [`imatlab`](https://github.com/imatlab/imatlab)). `pipenv install imatlab` breaks the dependency resolution for the lock file. So in my project where I use it, I'll already have instructions to deal install it, and it's clear to a dev who didn't have MATLAB installed.

Also since the piplock file resolution breaks everytime, I install new dependencies after the offending package (`imatlab` in this example) is part. So my workflow is to remove it, add the new dependency, then `pipenv install --skip-lock` the offending package again. It's a bit of a pain.
