### ISSUE TITLE
Freeze pipfile's dependencies

### ISSUE THREAD

**Issue by orihomie** [pypa/pipenv#4675]
Hi, I'd like to know how could I make pipfile's dependencies to lock on concrete package versions? 
Or how does pipenv behaves in case if there is pipfile.lock and there is not?

**Comment by thinkjrs** [comment]
@orihomie It sounds like you're looking for the `lock` command. See the docs [here](https://pipenv.pypa.io/en/latest/cli/#pipenv-lock). You can pin packages to specific versions when installing them and pipenv will handle the rest. 

And from another section of the docs:

> `pipenv lock` is used to create a `Pipfile.lock`, which declares all dependencies (and sub-dependencies) of your project, their latest available versions, and the current hashes for the downloaded files. This ensures repeatable, and most importantly deterministic, builds.

https://docs.pipenv.org/basics/#pipenv-install

Lastly, you can install from only a `Pipfile.lock` with `pipenv install --ignore-pipfile`. 

Hope this helps!

**Comment by orihomie** [comment]
But what if I've lost my ```Pipfile.lock```? Then installing dependencies only by pipfile would possibly break my project.

**Comment by thinkjrs** [comment]
> But what if I've lost my `Pipfile.lock`? Then installing dependencies only by pipfile would possibly break my project.

I believe this would be similar to losing your `requirements.txt`, as well, no? I agree that doing so could break your project.

Most of what I see (and do) in the wild using Pipenv for app development involves some type of versioning, i.e. `git`, and includes committing the `Pipfile.lock` to a local and/or remote repo of some sort, to avoid the problem you've pointed out.

Also, it is common to generate a `requirements.txt` file using Pipenv, so that `pip install -r requirements.txt` works to install packages from your `Pipfile.lock`. 

To do this, simply:
```
pipenv lock -r > requirements.txt
```

**Comment by orihomie** [comment]
Then why does pipenv print dependencies in Pipfile in a style:
```
[packages]
requests = "*"
```
Shouldnt it be just like that:

```
[packages]
requests
```

**Comment by ghoubrial** [comment]
Pipfile is used to give freedom to packages to update itself when installing on a fresh environment, but also limit them to specific versions when needed, usually we do this in a dev environment. You can specify a wildcard for a package so that any version can be installed or limit it to a specific version, for example, `requests = "=>1.0.0"` in case our app requires version `<2.0.0`. We don't want to specify `*` in Pipfile, so this will install the most recent version, which will definitely break our code, even if it is in a dev environment.

**Comment by orihomie** [comment]
@ghoubrial thanks for participating!
I dont know if you agree or disagree with me, but my point is that there must be some flag to freeze version of packages in a Pipfile and no, freezing to a pip's requirements.txt is not comfortable solution since I see it as an uncomfortable hook.

Maybe I'm just restricted by my experience but for me it became usual to manually edit Pipfile and still it peaces me off everytime.

**Comment by ghoubrial** [comment]
Actually, you can freeze versions of packages in `Pipfile`, and you should when your are app requires that! As I mentioned you can do `requests = "<=1.0.0"` or pin it to a specific version like `requests = "==1.0.0"`, and you can edit `Pipfile` manually like you do with `requirements.txt`. 

The purpose of `Pipfile.lock` comes when you want to deploy to Prod, you do not want to update packages versions when you install dependencies as this may cause your app to break, you need the exact same packages versions you used in development. 

As opposed to the dev environment, you should update packages versions when possible, so it is recommended to use `Pipfile` to install packages and not pinning dependencies to specific versions, since you still doing some development and likely running tests afterwards, so you can rest assured that everything works perfectly before saying that those are the versions that I want to use in Prod using `pipenv lock` and then installing them with `pipenv install --ignore-pipfile`. Hope that helps!

**Comment by thinkjrs** [comment]
In case it helps clear things up, here's an outline of my firm's usage of Pipenv: 

- All production dependencies + environments are generated via Pipfile.
- All development dependencies + development environments are generated via the Pipfile, as well. 
- For libraries we try not to ship pinned dependencies (so we attempt to avoid including a `requirements.txt` or `Pipfile.lock` for library code). Tox is your friend. 
- For application/service code we _pin via Pipenv's hashing mechanism_ into **both** `requirements.txt` and `dev-requirements.txt`, which are used to build container images. Do this with `pipenv lock -r > requirements.txt`, for example.
  - We use `pip install -r requirements.txt` (deployment service container) or `pip install -r dev-requirements.txt` (for our test build steps). 
  - This is _by design_ vastly superior to non-pinned code for _applications_ and allows **us to make reproducible builds**.  

> pip's requirements.txt is not comfortable solution since I see it as an uncomfortable hook.

In how I interpret this statement, I genuinely believe it to be an incorrect misconception. The process I've highlighted above is used in production for services that literally power the web and in mission critical apps for giant businesses.

I think a read of the advanced usage documentation might help clear this up. In particular, give the `Pipfile` vs `setup.py` section a read: https://pipenv.pypa.io/en/latest/advanced/#pipfile-vs-setup-py.

**Comment by orihomie** [comment]
Well, yes, there was a bit of misconception in my mind about pipenv since I've used to use it just as a comfortable pip + any virtual environment manager replacement. Doc says:
> For applications, define dependencies and where to get them in the Pipfile and use this file to update the set of concrete dependencies in Pipfile.lock. This file defines a specific idempotent environment that is known to work for your project. The Pipfile.lock is your source of truth. The Pipfile is a convenience for you to create that lock-file, in that it allows you to still remain somewhat vague about the exact version of a dependency to be used. Pipenv is there to help you define a working conflict-free set of specific dependency-versions, which would otherwise be a very tedious task.

So, I dont necessarily need to lock deps in Pipfile itself, instead just to be sure to never lose Pipfile.lock.
Locking deps in Pipfile is a case when I need to give a try to some recent versions of dependencies.  

Thanks for clearing things up!
