### ISSUE TITLE
Empty variable detection

### ISSUE THREAD

**Issue by gitpushdashf** [pypa/pipenv#4725]
It's really easy to not realize that an environment variable isn't being passed along. It'd be nice if pipenv would log a warning if you were using a variable, but it was zero-length.

I might be able to help write a patch for this.

**Comment by sravantit25** [comment]
Hi, I worked on this issue today and was able to fix it. However, I am unable to setup the development environment as mentioned in the Contributing guidelines. Because of this I am not able to write unit tests for my fix. But I have verified that it works. 

I will solve the environment issues, write a unit test for the fix and then raise a PR.

I am attaching a screenshot of the fix:

![fix_empty_variable_issue_4725](https://user-images.githubusercontent.com/62924721/125041578-88e04180-e0b6-11eb-836c-1015331038e6.PNG)

**Comment by matteius** [comment]
@sravantit25 is this out for PR?
