### ISSUE TITLE
`pip install --upgrade pipenv` doesn't update pipenv when in pipenv shell

### ISSUE THREAD

**Issue by haf** [pypa/pipenv#4769]
Wrote originally about problem similar to https://github.com/pypa/pipenv/issues/4642 but in fact the PATH:ness of pipenv prevented me to upgrade pipenv to get the fix for `pipenv install --pre` commands.

I've done `pip install --upgrade pipenv` and get no extra updates to pipenv, but when `pipenv shell` is present, it doesn't actually upgrade the symlink we use for pipenv itself and it doesn't forward the upgrade to the `pyenv`'s pip.

Maybe this is known and "wontfix", in which case you should just close it.

**Comment by SARANYA233** [comment]
can I work on this issue?

**Comment by matteius** [comment]
@haf I think you would have to ask `which pipenv` to see, because chances are you upgraded one in your virtualenv but your PATH is referencing one installed at a global system level.   As for pyenv, that is a different project.   Virtualenv will copy in the current version of pip and python when they are created, so often you'll have to recreated them after you upgrade python or possibly even pip.  I have some addition in my .bashrc to be able to use my user installed pipenv, and I uninstalled my global pipenv.
`export PATH=/home/mdavis/.local/bin:$PATH`
