### ISSUE TITLE
pipenv migration to vendoring from invoke.

### ISSUE THREAD

**Issue by oz123** [pypa/pipenv#4914]
pipenv currently bundles a lot of Python packages. The mechanism and policy to update these and remove obsolete
packages are not clear (e.g. is yaml3 still needed? when we add a vendored package, is there a linked issue?)

It seems that the mechanism with invoke was copied from upstream pip. However, pip itself has since migrated
to [vendoring](https://pypi.org/project/vendoring/). In their words:

```
pip had a "home-grown" setup for vendoring dependencies. The invoke task grew in complexity  
to over 500 lines and, at some point, became extremely difficult to improve and maintain.
```

Using vendoring should allow benefiting from upstream work and maybe even contribute to it.

I am able to start working on this, question is if this possibly requires an official PEEP. I am not yet and official maintainer, so I can't
even submit such PEEP. But I am able to contribute the code for it.

**Comment by matteius** [comment]
@oz123 with my more recent work on using invoke, I am not sure that we can drop invoke at all because we have our own invoke tasks for managing all of our vendor depdenencies, not just pip.   Plus that document says `The invoke task grew in complexity to over 500 lines and, at some point, became extremely difficult to improve and maintain` however the invoke task we use to vendor pip is just part of this file https://github.com/pypa/pipenv/blob/main/tasks/vendoring/__init__.py#L741
I am not sure they are referring to the same thing? 

The other potential problem I see is with the necessary patched imports and minimal patches we make to pip.  Actually the hardest part of updating to pip 22.0.4 vendoring (beyond the bugs of pip 22.0.3) was dealing with updating the .patch files correctly.  Fortunately the vendoring part of the CI tests that it can recreate the process and apply those patches.

Also tangentially, I am not sold on the PEEP system for making improvements to this project.  Or I should say, it doesn't seem to be a true requirement to making changes -- probably best left for overhauling something major which I am not sure modernizing our internal development processes in the project should require a PEEP or who would even review if it did.

**Comment by oz123** [comment]
Good point about invoke. I was not sure about it too. Just thought it's worth discussing.
As for patches:
They are a burden and debt, and if we can upstream the patches, we will do everyone a favor.
I am also not fond of the PEEP process as is. As long as it's two of us under the scrutiny of @frostming we don't need it.
We can have (or not) a consensus more easily. If this project is going to have a larger community of maintainers, we can re-consider.
It is also possible to have other models, e.g. Linux kernel and subsystems. I don't want and I don't feel comfortable 
with stuff related to Windows. And I am happy to lead other areas. If other people join and this grows, we can think of a model which has "subsystems" leads.
