### ISSUE TITLE
Pipenv seems to cache old Python interpreters and use them even if they don't exist [anymore]

### ISSUE THREAD

**Issue by superlazyname** [pypa/pipenv#4952]
## Background
A Windows machine has two interpreters on it, one at C:\Python_A\ (I'll call this pythonA) and one at C:\Python_B\ (I'll call this pythonB). 
- We don't really want to use pythonB with Pipenv, but it seems to get pulled in and I'm not sure how to get rid of it.
- Both python interpreters are the same version, if it matters.

I have had a few people go through this process on a couple different machines

1. They install pipenv using `pythonA -m pip install pipenv`
2. They try and use Pipenv (`pipenv install`, etc), the person gets strange errors, I investigate
3. I notice that Pipenv seems to have found pythonB as an interpreter and it's trying to use that instead of pythonA.
4. We notice that and take pythonB completely out of PATH, we try the pipenv command again
5. pipenv and pythonfinder still find pythonB
6. Just as an experiment, we delete/uninstall pythonB from the system completely
7. pipenv still finds pythonB, pythonfinder does not
8. Uninstall and reinstall pipenv
9. pipenv now only finds pythonA (which is what we want)

Note: To try and investigate this I installed pythonfinder separately and played around with that, because I notice that Pipenv uses that internally. 
- It wasn't the "vendored" pythonfinder included in Pipenv, though.

## Expected behavior
- Pipenv would just use PATH to find python interpreters

## Question
Does pipenv scan for python interpreters when I (re)install pipenv and cache that somewhere? 

If so how do I remove interpreters I'm not using anymore?

## What we tried

It sounds like there's at least two caches, maybe written as files in the filesystem?
- A pythonfinder cache (because it still found pythonB even though it wasn't in PATH)
- A pipenv cache (because it found pythonB even though it wasn't even on the system anymore)
- Maybe a venv/pyenv cache?

So if this cache exists, how do I clear it? I'd rather not tell people to uninstall pythonA and reinstall Pipenv if there's a better option. 

We tried to find / clear this cache by:
- `pipenv lock --clear`
- Looking in Pipenv's AppData directory
- Looking in the registry (does not seem to be anything)
- Reading the source code of Pipenv and pythonfinder (maybe there's some shared state in click but I didn't see anything)

I don't know if this is a question or a bug, depends on whether this is "intended behavior" or not. This wouldn't make for a great SO question either, too esoteric at this point. I'm running out of ideas though, sorry. If you know offhand if Pipenv and/or pythonfinder caches Python interpreters and you can say "yes the file is at C:\whatever\cache.json" that would be a huge help.

Also we're using pipenv 2020.11.15.

**Comment by oz123** [comment]
Windows has crappy support for symlinks.
https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

I believe it's because when you created the virtual environment with pipenv, it actually copied the unwanted python version. To fix this, you first have to set the path correctly, and then create a virtual environment with pipenv.
As a side note, please use WSL.. It's the best way to develop software on windows with out leaving Windows.

**Comment by oz123** [comment]
Another side note, please update to the latest version of pipenv. The version you have has a known CVE.

**Comment by superlazyname** [comment]
@oz123 Do you know where it would have copied it to, or where it was trying to symlink to?

**Comment by oz123** [comment]
It copies it to the virtual environment. Somewhere under user data in windows. I'm not sure exactly where, check the documentation for windows.

**Comment by superlazyname** [comment]
@oz123 which docs? Virtualenv? pyenv? Pipenv?

As I mentioned, I tried searching all over for this, and looking in AppData and the registry. That's why I made this issue, I even read the source code for Pipenv and Pythonfinder.

If you don't know please assign this to somebody else or reopen it, thanks.

**Comment by oz123** [comment]
Python isn't stored in the registry, it's somewhere where pipenv is creating its virtual environments, there is CLI option for that that should work on Windows:
```
$ pipenv --venv
/home/oznt/.local/share/virtualenvs/tiny-cms-klxvrO_k
```

You can find which python is in there with:

```
$ ls -l /home/oznt/.local/share/virtualenvs/tiny-cms-klxvrO_k/bin/python* # replace ls with whatever works on windows

lrwxrwxrwx 1 oznt oznt 19 Jan 16  2021 /home/oznt/.local/share/virtualenvs/tiny-cms-klxvrO_k/bin/python -> /usr/bin/python3.7m
lrwxrwxrwx 1 oznt oznt  6 Jan 16  2021 /home/oznt/.local/share/virtualenvs/tiny-cms-klxvrO_k/bin/python3 -> python
lrwxrwxrwx 1 oznt oznt  6 Jan 16  2021 /home/oznt/.local/share/virtualenvs/tiny-cms-klxvrO_k/bin/python3.7 -> python
lrwxrwxrwx 1 oznt oznt  6 Jan 16  2021 /home/oznt/.local/share/virtualenvs/tiny-cms-klxvrO_k/bin/python3.7m -> python
```
You can see my Python list above is symlinks. Since, windows does not support symlinks, I don't know what it does.
You can look at the code of `venv` module in the Python STL to figure it.

If this works, I'd appreciate if you could add this information to the material in:
https://pipenv.pypa.io/en/latest/install/#virtualenv-mapping-caveat

As it does lack information on Windows. 

> Windows is a first-class citizen, in our world.

No, windows is not a first class citizen anymore. Just because of the circumstances. I can't help this. If more people step up to maintain this project, then, yes, this sentence could be true.

Pipenv is a volunteer based effort. Currently, there are two active maintainers, only one of them uses windows.
If he does not know, then bummer. The amount of windows support issues here is enormous, and these are mostly not pipenv related, rather Python or OS related.

Outside this project, many developers prefer not to work with Windows.  As you can see, for example, from the Stackoverflow developer survey: 45% of the developers prefer working with Windows, while slightly more than 50% prefer working with Mac or Linux:

![image](https://user-images.githubusercontent.com/1083045/153867822-f5db4eb5-bf51-4e70-9d6c-ce853b4a2b85.png)

The interpretation of the results in the image is somewhat weird, as what counts, isn't the single position of Windows, but rather the amount of developer who prefer not working with it.

This is not to shame people who use Windows (I guess many of them don't even have the choice). It's just to tell you how the reality is, and if you want to change it, you are welcome. It's an open source project.

**Comment by superlazyname** [comment]
> No, windows is not a first class citizen anymore. Just because of the circumstances. I can't help this. If more people step up to maintain this project, then, yes, this sentence could be true.
>
> Pipenv is a volunteer based effort. Currently, there are two active maintainers, only one of them uses windows.
If he does not know, then bummer. The amount of windows support issues here is enormous, and these are mostly not pipenv related, rather Python or OS related.

OK, I understand. Maybe soon, somebody will help you with this.

> "Windows is a first class citizen in our world".

Is a very bold claim considering Python itself doesn't always consider Windows a first class citizen. I recommend updating the docs, saying something like.

> "Pipenv has known issues in Windows. Linux is our primary target platform, we could use your help to make Windows a supported platform"

Realistic scope in the docs can help set everyone's expectations.

As somebody who's been messing with Python in Windows for a while,
- I can agree that there's a good bit of flakiness in general, it's sadly not a strong foundation
- There is in general a "hole" in support around where environments intersect with Windows.
- I use Linux as my primary OS at home, we don't have a choice in using Windows elsewhere.
- Trying to automate environment creation like Pipenv does on Windows seems... ambitious.
- I have noticed that Windows tends to require a lot of erm... custom, and creative coding. A lot of Python packages make Linux-y assumptions.

**Comment by superlazyname** [comment]
Sorry just remembered something, will post it here in case it helps,

> I believe it's because when you created the virtual environment with pipenv, it actually copied the unwanted python version.

> Looks like maybe %USERPROFILE%\.virtualenvs (C:\Users\<your name>\.virtualenvs)

I don't think this is the behavior I noticed, the version of Python that we were seeing was not in this subdirectory. It seems that some part of Pipenv (or one of its dependencies) cached **the path** of the interpreter somewhere, and didn't copy the interpreter.

I have seen folders in the .virtualenvs folder containing Python.exe and this is the expected behavior for me, I was not expecting to see it pull in a Python.exe that wasn't in PATH or in .virtualenvs, though.

**Comment by matteius** [comment]
@superlazyname Did you install `pipenv` locally or globally?  See `which pipenv`:
`/c/Users/matte/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/Scripts/pipenv`

When I run with a locally installed `pipenv` on Windows 11 and the Python 3.10.2 image from the Windows Store (which is what git shell opened up when I typed Python on a fresh install). I find that `which python` is the virtualenv python:
```
$ pipenv run which python
/c/Users/matte/.virtualenvs/mainegardener-R_3nKGL4/Scripts/python
```

Some tips for Windows, I think you'll overall have a better experience using the Git shell for windows than the built in cmd prompt, but prove me wrong (I can do a test on that shell too).  Some tips for working with python/pipenv in Git shell.  Python wasn't rendering to the terminal until I added this to my `~/.bashrc`:
```
alias python='winpty python.exe'
alias pipenv='winpty pipenv.exe'
```
Second, you might also need to run `bash` 

I suspect perhaps you have a system install of pipenv that is able to find the system python?
