### ISSUE TITLE
Allow `pipenv sync` to try alternative pip index urls as long as hashes match.

### ISSUE THREAD

**Issue by mungojam** [pypa/pipenv#5041]
### Is your feature request related to a problem? Please describe.

As discussed on https://github.com/pypa/pipenv/pull/5029#issuecomment-1093817358, we would like the ability restored to run `pipenv sync` against multiple potential pip package indexes. This is to enable us to move builds between different environments which have access to different packages sources (for example pypi vs. an internal pypi cache vs. GitHub packages once they add pip support).

### Describe alternatives you've considered

My alternative is to rewrite the pipfile.lock with the alternative locations before running `pipenv sync`, depending on the environment which is a big hack.

### Other context

#5039 has been kindly created by @matteius to cover this, so I will try that out

**Comment by matteius** [comment]
@mungojam Any updates on your end if that branch is effective?  Still want to settled in on the option name and get it added to the documentation once we know that works.  I don't have a great unit test lined up either.   Will want to get this queued up soon because we are pending the dropping of python 3.6 and the vendoring of pip 22.0.4 to try and get another release out for your use case before then.  Our target for that other work is end of April.

**Comment by mungojam** [comment]
> @mungojam Any updates on your end if that branch is effective? Still want to settled in on the option name and get it added to the documentation once we know that works. I don't have a great unit test lined up either. Will want to get this queued up soon because we are pending the dropping of python 3.6 and the vendoring of pip 22.0.4 to try and get another release out for your use case before then. Our target for that other work is end of April.

I got part way through testing it, I'll try and get it finished today

**Comment by matteius** [comment]
Awesome, thanks @mungojam for that update!  I was worried about dropping 3.6 support since I knew you requested both things, but this is helpful that dropping 3.6 won't be a blocker for you on this one.
