### ISSUE TITLE
pipenv will fail to install package in docker container

### ISSUE THREAD

**Issue by tailordevs** [pypa/pipenv#5290]
Im using ubuntu base image and installing some package on it make our required docker image.

I faced issue that packages are installing which was working fine some days back so I tried whole day to check where is the problem and finally identify that Pipenv not installing package in docker container if we are using version>2021.11.23.

**Dockerfile**
```
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=nonintercative

RUN apt-get update && apt-get install --no-install-recommends -y git python3.9 python3-pip python3.9-dev curl python3-dev gcc libcurl4-openssl-dev libssl-dev jq && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && echo "Asia/Kolkata" > /etc/timezone && mkdir -p /var/run/celery && mkdir -p /var/log/celery/  && mkdir -p /var/www/oms && ln -s /usr/bin/python3 /usr/bin/python

RUN pip install pipenv && pip install -U setuptools && pip install --upgrade awscli

WORKDIR /var/www/oms/

COPY . .

RUN pipenv install --system --deploy
```

**Pipfile**
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
celery="==5.2.3"

[dev-packages]

[requires]
python_version = "3.9"
```

**Comment by matteius** [comment]
Interesting, I did some triaging and it turns out that the sysconfig patch I added to get past a setuptools issue is causing this behavior:  https://github.com/pypa/pipenv/pull/5275/files#diff-e154923a3c93acd48d40dd714127c4b90cac776ebd71930770919d539d137f77R44
The good news is that based on a conversation with setuptools I got some new ideas to try and prevent importing setuptools in pipenv, and making those changes in this PR allows me to revert that patch, solve the setuptools problem, and it also solves your example problem where those packages get installed to a seemingly different site packages. https://github.com/pypa/pipenv/pull/5289 

I cannot estimate an exact release date yet, because to make that change for real I need to make the corresponding change to requirementslib, release that and vendor in the new version into the above PR.

**Comment by blancsw** [comment]
Thanks for your answer ! I got the same issu

**Comment by matteius** [comment]
This is the target PR -- ran into some merge conflicts on the other one:  https://github.com/pypa/pipenv/pull/5228

**Comment by matteius** [comment]
`pipenv==2022.8.24` has been released 🎉
