### ISSUE TITLE
Pipenv version 2022.8.31

### ISSUE THREAD

**Issue by dehhganii** [pypa/pipenv#5374]
### Issue description

We work on a project which uses pipenv. In the version 2022.8.31 the building in Jenkins get failed. When I specify the version in our code the build is fine. However, all versions after 2022.8.30 make the build failed.
### Expected result

The build should pass with no error
### Actual result

The build failed due to: hudson.AbortException: script returned exit code 1

![image](https://user-images.githubusercontent.com/23422526/191969900-91857fca-a26c-481b-a801-81d3fdb8d75e.png)

**Comment by matteius** [comment]
@dehhganii I would need to see more of the `--verbose` output to try to determine which package, basically I believe this is similar to #5332 #5340 #5354 and #5358 -- there is likely some dependency that a setup.py imports which is not available during the install phase because it too is being installed.   #4745 will provide better support for specifying arbitrary package install groups such as prereqs so that you can manage pre-install dependencies that way, but for now the guidance is to `pipenv run pip install <package>` for the package that is required by another setup.py to be installable.

**Comment by dehhganii** [comment]
Hello Matt,
Thank you for the response. I am copying the part of the log I get from the
first error. It is tooo long.

[image: image.png]

**Comment by matteius** [comment]
@dehhganii I feel that there would be some other error in the `pipenv sync --verbose` output.   Since the hashed packages installed as a group there is no good way to determine from the above output which package is causing you the install troubles.

**Comment by dehhganii** [comment]
Based on new investigation we did the **one** problem is that the  hash-code does not get generated in updating pipfile.lock. As it is in these issues: https://github.com/pypa/pipenv/issues/5021
https://github.com/pypa/pipenv/issues/5053

**Comment by matteius** [comment]
@dehhganii Just saw your response -- both of those issues are marked closed, but related to the use private pypi repositories and the requirement to have deterministic index restricted packages.   It should still be possible for your use case to define the `Pipfile` in a way that correctly defines the index mapping for your packages.   Let me know if you need help sorting this out, I'd be happy to help on the Python Developers slack group.
