### ISSUE TITLE
pipenv install --deploy now fails after having worked for months

### ISSUE THREAD

**Issue by Nick-Yazdani** [pypa/pipenv#5392]
### Issue

pipenv install --deploy now fails in my docker build step due to out of date lockfile. 

However whenever I run pipenv lock, it fails to update the hash and instead spits out the original hash that it already was.

### Expected

I expect the dependencies to install, as they have been for almost 6 months with no issue.

### Actual result
```console
✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/-x-v5uFv0
Your Pipfile.lock (ab547e) is out of date. Expected: (9d352e).
Usage: pipenv install [OPTIONS] [PACKAGES]...

ERROR:: Aborting deploy
```
### Steps to replicate

- RUN pipenv install --deploy (in a Docker build step, having copied in the Pipfile and Pipfile.lock)
-------------------------------------------------------------------------------
[output.txt](https://github.com/pypa/pipenv/files/9742751/output.txt)

**Comment by matteius** [comment]
@Nick-Yazdani You are failing on the hash check -- when is the last time you relocked?  It worked when when I re-locked your Pipfile in my testing.

**Comment by Nick-Yazdani** [comment]
@matteius I relocked several times but it just kept reverting back to the previous hash that was out of date. I think perhaps there is an issue with my system configurations rather than pipenv. (Perhaps my use of pyenv etc.). Feel free to close the issue.

**Comment by matteius** [comment]
@Nick-Yazdani Would love to see us figure out the root of the problem -- we can leave it open for now.   Do you have a prior version of pipenv that this works with your existing setup on?   Are you on latest ubuntu?

**Comment by Nick-Yazdani** [comment]
It was working with whatever release the docker build step was pulling prior to today, sorry I just pull the latest in my build step so I'm not exactly sure of the pipenv version. Everything works fine on my local its just the docker build part that is causing issues. I'm on Ubuntu 20.04. 

As a sanity check I will run the build on our GCP pipeline and see if it fails the same way, that way we can narrow it down to my OS?

**Comment by Nick-Yazdani** [comment]
It failed in the GCP pipeline, and that build had previously succeeded (yesterday). I ran it on the last successful commit, the image it uses is python:3.9-bullseye. Perhaps this only happens when building in a Docker environment?

**Comment by matteius** [comment]
@Nick-Yazdani The biggest changes between the `2022.9.4` and  `2022.9.10` were in the named package categories PR.   That might explain a possible new hash generation.  When I diff the lock file I generated and the one in your output file, I see the only change is with the markers, which was a few releases ago fixed to always generate the same markers.   Perhaps the markers affected the hash generation.  If it has been several months since locking there are a few reasons that come to mind a new hash maybe generated.

Could you describe more about:
>  I relocked several times but it just kept reverting back to the previous hash that was out of date.

How does it revert back to the prior hash, in what step?

**Comment by matteius** [comment]
@Nick-Yazdani For debugging purposes, would you be able to change the Pipeline to `pipenv sync` instead of `pipenv install --deploy` which verifies the hash.  I would like to narrow down if its failing on simply the hash validation, or anything additional in the install phase.

**Comment by Nick-Yazdani** [comment]
I downgraded to the previous release on my local system and now it works. I will however as a courtesy reinstall the newest release and do what you have asked so as to be of help :)

**Comment by matteius** [comment]
@Nick-Yazdani Can you share part or all of the Dockerfile that builds this?

**Comment by Nick-Yazdani** [comment]
@matteius I can't get it to break now even on the latest (it installs perfectly and so does sync option), I think the issue was that for some reason when I ran pipenv lock with the newest release it wasn't actually updating the hash as evidenced by the output being the same out of date hash that it began with.

When I downgraded to the previous release and ran pipenv lock, it successfully updated the hash and thus now has resolved the problem.

**Comment by Nick-Yazdani** [comment]
```console
FROM base AS python-deps

RUN python -m pip install --user pipx && python -m pipx ensurepath

SHELL ["bash", "-lc"] 

RUN pipx install pipenv

COPY Pipfile .
COPY Pipfile.lock .
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
```

**Comment by matteius** [comment]
@Nick-Yazdani Ah wow, thank you for your report -- somehow in your example lock file, re-locking it doesn't update the hash.  This is definitely going to be related to the named categories work, there were a number of places I had to refactor how the lock file was accessed and updated, so I am sure that this is it.  Thanks for your help in pin-pointing the issue.
```
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5392$ pipenv install --deploy
Your Pipfile.lock (ab547e) is out of date. Expected: (9d352e).
Usage: pipenv install [OPTIONS] [PACKAGES]...

ERROR:: Aborting deploy
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5392$ pipenv lock
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (2f38753c2c827a9636d10619569c9aa25970d6fcade1f04d3758edebd0ab547e)!
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5392$ pipenv install --deploy
Your Pipfile.lock (ab547e) is out of date. Expected: (9d352e).
Usage: pipenv install [OPTIONS] [PACKAGES]...

ERROR:: Aborting deploy
```

**Comment by matteius** [comment]
@Nick-Yazdani I opened a PR that I think addresses the issue -- the fix is to always re-write the meta section of the generated lockfile dictionary, prior to writing it to the file.  I am not sure how it ever worked in the prior implementation, but I don't imagine this causing many other issues (though one test is failing with this change).  Will run through test suite and think through it some more, if possible will cut a new release tomorrow.

**Comment by hq9000** [comment]
Hi all! I confirm this issue. We didn't change our Pipfile, only upgraded pipenv and now many of our locks are considered "out of date". 

I don't think this change of the logic of hashing the Pipfile is intentional (or is it?). 

Regardless of the above and more generally, it looks like depending on the "latest" Pipenv is not a reliable way forward. If so, what would be the right way to get the maintained version of pipenv without risking to face a breaking change/bug?

**Comment by matteius** [comment]
@hq9000 I am not sure that `2022.10.9` would have changed the `Pipfile` hashing, though it is possible -- it seems more likely to me that the hash change was caused by the conversion to `plette` a few releases ago, if so, that was definitely a side-effect of an intentional change and path forward for pipenv since we lacked rights to maintain the prior `pipfile` library that was in use. 
 
The known regression here is updating the lock file doesn't update the meta hash in all cases -- I have a PR out for that.   That would also affect anyone that relies on updating the lock file as part of the steps their CI took.   If you can provide additional details, it would be helpful for understanding the issue at a deeper level the issue with the hash changing.

> Regardless of the above and more generally, it looks like depending on the "latest" Pipenv is not a reliable way forward. If so, what would be the right way to get the maintained version of pipenv without risking to face a breaking change/bug?

We do try to not have breaking changes, but that being said, `pipenv` is being primarily being maintained myself and Oz outside of our full time jobs -- in this case it is something our test suite did not pick up on.  I knew there were risks with the named package categories feature changes, which is why I cut the release on a Sunday morning to a lot some time to try and get a follow-up release if/when necessary.  Some developers will run with the latest pipenv release until there is an issue and then pin until the issue is resolves--this is probably recommended.   Otherwise you can pin indefinitely and periodically perform testing/validation and upgrade to a newer version.   We could explore pre-releases more if we had a pool of people helping test those before a major release, but simply put, with the versioning scheme we inherited we would likely need to further change our development workflows further to support this.

**Comment by matteius** [comment]
I just did some further testing with the original example, and it seems somehow the named package categories changes the data the Pipfile lock gets computed on.   I am looking further into this.

**Comment by matteius** [comment]
I think I found the issue -- `plette` is including now the `pipenv` section if you have it present in the `Pipfile`.   I have a fix for that as well -- will require some additional work to get a new version of plette released, but it can be done.

**Comment by matteius** [comment]
Sorry for those issues folks -- `pipenv==2022.10.10` has been released which includes the fix for the Pipfile hash changing, and also the fix for the metadata writing to the lock file at the end of the lock phase.

 @Nick-Yazdani the hash generation changed back to how it was before -- you may need to re-lock again to get back to that point.

**Comment by matteius** [comment]
`pipenv==2022.10.11` is released and reverts back to build isolation by default, since it is possible for users to pass `--extra-pip-args="--no-build-isolation"` but it is not possible to retract it if it is supplied by default, this was part of the decision.

**Comment by matteius** [comment]
@NeroVanbiervliet I suspect that is an unrelated issue and would have started happening in `2022.8.31` -- if the new `2022.10.11` doesn't resolve it for you (probably won't) then please open a new issue report for your issue and we will provide support.  Likely there is a setup.py that requires something else -- see if you can get more information for your new issue report with `pipenv sync --verbose`.
