### ISSUE TITLE
2022.10.25 is not in pypi

### ISSUE THREAD

**Issue by gitpushdashf** [pypa/pipenv#5443]
Hi,

Was looking forward to trying out 2022.10.25, but it looks like it didn't make it to pypi.

Thank you!

**Comment by matteius** [comment]
@gitpushdashf Thanks for your report -- I have pushed the corrected tag and it's built now.  https://pypi.org/project/pipenv/2022.10.25/

@oz123 It looks like the release earlier ended up being published as a pre-release `2022.10.13.dev0` -- I re-ran the release command `pipenv run invoke release.release` and deleted the existing tag because somehow that did get tagged with v2022.10.25 in the repo.   Perhaps you ran different commands to generate the release?

**Comment by gitpushdashf** [comment]
Great, thank you so much!
