### ISSUE TITLE
Most bit.ly Links Scan as Malicious and Cause False Positives

### ISSUE THREAD

**Issue by Robotsalesmen** [pypa/pipenv#5646]
When scanned with software security scanners (e.g., guarddog, etc.) code containing bit.ty links scan as malicious.

This holds true for the code:  

      self.link = 'https://bit.ly/3OY2wEI'

I provided this information for general edification.

You might consider replacing bit.ly usage.

**Comment by matteius** [comment]
@lemuelkn Care to take a shot at this cleanup task?

**Comment by lemuelkn** [comment]
Sure, how can I help?

**Comment by matteius** [comment]
Looks like there are a couple spots in the code base that reference bit.ly links -- the goal is to find them and update them to be either corrected, or if no longer applicable to remove that part from the documentation.

**Comment by lemuelkn** [comment]
Should there be a warning or an exception thrown when the user tries to pass in a bit.ly link?

**Comment by matteius** [comment]
@lemuelkn I don't think that is the issue, the issue is that there are a couple spots checked into the code base that reference bit.ly.    This was supposed to be an easy ticket to get started, but now that I look more closely, the links are in patched safety and also in pip -- which we don't want to patch these.   @Robotsalesmen can you report your issue to the upstream projects so we can vendor in future versions that don't have the shortened links?

**Comment by lemuelkn** [comment]
Oh okay, I will look at some of the other contributor candidates, or you can let me know about some other tickets. Thanks @matteius !
