### ISSUE TITLE
Another possible `install_search_all_sources = true` regression

### ISSUE THREAD

**Issue by monkeyman192** [pypa/pipenv#5781]
There is this associated issue: https://github.com/pypa/pipenv/issues/5743
It was closed, but I think this is a little different so figured I'd raise a new issue for it...

### Issue description

In pipenv version 2023.6.18 (and onwards), attempting to run `pipenv sync --dev` (`--dev` flag likely unimportant) raises an error only when the following is in the pipfile:
```
[pipenv]
install_search_all_sources = true
```
I have a number of dependencies in private repos and all have their repos explictly specified, as well as any sub-dependencies which are also in our private repo. The issue is NOT with locking. This works perfectly fine. The issue is only when calling `sync`.

### Expected result

I'd not expect this flag to affect syncing, least of all cause it to fail.

### Actual result

```
Installing initially failed dependencies...
Looking in indexes: https://pypi.org/simple, <private_index_url_1>, <private_index_url_2>, <private_index_url_1>, <private_index_url_2>
...
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement <private_repo>==0.1.dev19+g92d125f (from versions: none)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for <private_repo>==0.1.dev19+g92d125f
ERROR: Couldn't install package: [Requirement(_name='alembic', vcs=None, req=NamedRequirement(name='alembic', version='==1.11.1', req=Requirement.parse('alembic==1.11.1'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=alembic, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.11.1, ...
```

(yes, the private repo urls are listed twice like that... Looks a bit weird...)

### Steps to replicate

See description.
Locking the file works fine in all versions. All the dependencies are resolved correctly and the lock file looks correct (private dependencies have the correct index urls in the lock file).
Running `pipenv sync --dev` in version 2023.6.18 onward fails when `install_search_all_sources = true` is present, but passes when it isn't, whereas 2023.6.12 has no issues.

This isn't the biggest issue as it's easy to remove and we don't need it since we have all the dependencies specified, but it did take a while to figure out why it was happening, and I'm mostly confused as to why this is even happening...

**Comment by matteius** [comment]
Admittedly I was confused too when I had to update the integration tests to not use the `install_search_all_sources = true` option with https://github.com/pypa/pipenv/pull/5737

I believe what is happening is that in the `install_search_all_sources = true` code path, all indexes are available for pip to search for the install, but with my patch related to https://github.com/pypa/pip/issues/11784 causes the search scope to be reduced to just the first index -- it is because the index lookups aren't passed during install (because its not a real pip feature yet) it gets restricted from finding what its looking for because its simply not in the lookup dictionary.   I evaluated trying to add it, but it the proper way would be supporting it in pip to pass the `--index` per requirement line being specified for install -- this is basically what the batch install logic in pipenv does when `install_search_all_sources = false` which is the default behavior.

**Comment by matteius** [comment]
I would be curious if your result @monkeyman192 is any different with the newest pipenv release from today.

**Comment by monkeyman192** [comment]
@matteius I just tried with `2023.8.20` and still the same issue.

**Comment by matteius** [comment]
@monkeyman192 I've opened a branch that amends the pip patch to not default to the default index (except during the resolver) so the `install_search_all_sources` should work again in the above tagged branch.   Would be helpful to get someone with that issue to help verify it.

**Comment by monkeyman192** [comment]
> @monkeyman192 I've opened a branch that amends the pip patch to not default to the default index (except during the resolver) so the `install_search_all_sources` should work again in the above tagged branch. Would be helpful to get someone with that issue to help verify it.

Sure, I'll pull it and try it out, thanks!
