### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by jeffwidman** [pypa/pipenv#5819]
I couldn't find an existing issue tracking dropping support for Python 3.7 (which was EOL'd at the end of June).

To be clear, I have no "user" need for this, it's more about making the lives of maintainers easier.

FWIW, we will be dropping support in :dependabot: later this month (and going forward tentatively hope to start aligning to the upstream Python support lifecycle), so as part of that work I was auditing the Python package managers. `pip-tools` / `poetry` already dropped `3.7`, so the overall packaging ecosystem is moving away from `3.7` pretty quickly.

**Comment by matteius** [comment]
@jeffwidman actually I have been thinking to not drop py 3.7 until we move off requirementslib, because we wanted to have a good path forward for python 3.7 and Depndabot being able to make use of the `pipenv upgrade` command.  Plus this work fixes a number of other edge cases around how how handle extras:  https://github.com/pypa/pipenv/pull/5793

Its kind of some lessons learned from dropping 3.6 too soon; by ensuring we migrate the code base and fix any critical issues in a final release before saying good by to 3.7 will be helpful to folks trying to upgrade past 3.7

**Comment by oz123** [comment]
This is actually done.
