### ISSUE TITLE
Avoid creation of Pipfile

### ISSUE THREAD

**Issue by buhtz** [pypa/pipenv#6047]
My project do use a pyproject.toml. I see no need for a pipfile.
But it is always created. I might misunderstand its purpose.

Its content does seems useless to me. None of that is related to the local repo/project I used that virtual environment for.
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.11"
```

**Comment by DanielSwain** [comment]
Pipenv uses Pipfile.  Poetry might be a better option for you if you would prefer to use pyproject.toml.

**Comment by buhtz** [comment]
But according to the content of that Pipefile in my example it doesn't seem to me that pipenv do use it. It's content is not related to any of my projects meta data. What is the purpose of such a file?

pyproject.toml is PEP standard. There is no way around it.

Poetry is per design not PEP conform and also more then just a env handler. It is not an option.

**Comment by DanielSwain** [comment]
[Pipfile](https://github.com/pypa/pipfile) was proposed some years ago to replace requirements.txt, but it seems that the industry is moving to pyproject.toml.  Pipfile is fine for projects that are not libraries, but pyproject.toml is necessary for projects that are libraries, so I think that's why people seem to be moving to that format - it covers EVERY type of project you might want to do.  In the pipenv repo, you will see one pyproject.toml file for that reason - pipenv is a library, and pyproject.toml is necessary to provide the information for creating the pipenv library files (the Pipfile format does not include all of the necessary information like pyproject.toml does).  I suggested Poetry because it actually uses pyproject.toml in the same way that pipenv uses Pipfile (and instead of Pipfile - or any other format for that matter) and so Poetry can be used for regular projects OR projects that are libraries.

**Comment by buhtz** [comment]
I do use pipenv to manage virtuel environments not the build process.
In my understanding, no matter if it is pipfile, requiremens.txt, pyproject.toml or something else, these files are irrelevant for the managment of a virtual environment.

I still don't get why pipenv do use such a file. Where is the relation to a virtual environment?

**Comment by DanielSwain** [comment]
`pipenv` can read from a requirements.txt if you want to use that for the initial setup of an environment, but it will still write out a Pipfile and a Pipfile.lock because these two files are the main ones that were chosen by the original creator of `pipenv` as the format in which to store information about which packages are installed in a particular venv.  Pipfile includes all of the main packages that you install in a environment (via `pipenv install`), and Pipfile.lock describes EVERY package (and it's currently isntalled version) that is installed in the environment (remember that `pipenv` automatically installs every dependency of any package that you install using `pipenv install package_name`).  In production, you would then do `pipenv sync` to create or update the venv.  `pipenv sync` uses `Pipfile.lock` to (re)create the venv.

**Comment by buhtz** [comment]
I really do not see the advantage. I do have pip and a pyproject.toml for all that.
But thanks for your explanations.

**Comment by chriscarrollsmith** [comment]
I also am experiencing this problem. I have a project that uses poetry for dependency management, yet for some reason a Pipfile keeps getting auto-created in the project root. I'm not sure what's causing this. I don't seem to have any pipenv-related VSCode extensions running.

**Comment by chriscarrollsmith** [comment]
@buhtz I figured it out. It is the Pytest IntelliSense extension in VSCode that is causing this. The extension requires you to set a `pytest.command` setting. If you don't set this setting, the default value is `pipenv run tests`. And if that's the value you're using, then the extension apparently creates a Pipfile every time you view one of your tests.

**Comment by JoeDonMalone** [comment]
@chriscarrollsmith What  exactly did you set your pytest.command setting to? I have just started having this issue, and can't get it to stop. Its very obnoxious

**Comment by chriscarrollsmith** [comment]
> @chriscarrollsmith What exactly did you set your pytest.command setting to? I have just started having this issue, and can't get it to stop. Its very obnoxious

I just uninstalled the extension, but I imagine you could do "poetry run pytest tests" if you're using poetry, or whatever is the equivalent command to run pytest with your virtual environment without activating it first.
