### ISSUE TITLE
No module named 'pipenv.vendor.pipdeptree._detect_env'

### ISSUE THREAD

**Issue by bertek41** [pypa/pipenv#6305]
### Issue description

Latest release has an error:
```
Successfully created virtual environment!
Virtualenv location: /github/home/.local/share/virtualenvs/workspace-0SCQBxY3
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (8d[26](https://github.com/*****#step:6:27)6f)...
All dependencies are now up-to-date!
Error running command: $ 
/github/home/.local/share/virtualenvs/workspace-0SCQBxY3/bin/python 
/usr/local/lib/python3.11/site-packages/pipenv/vendor/pipdeptree -l --reverse 
--json-tree
STDERR: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File 
"/usr/local/lib/python3.11/site-packages/pipenv/vendor/pipdeptree/__main__.py", 
line 16, in <module>
    from pipenv.vendor.pipdeptree._detect_env import detect_active_interpreter
ModuleNotFoundError: No module named 'pipenv.vendor.pipdeptree._detect_env'
```

### Steps to replicate

Latest release "pipenv-2024.3.1" has this bug. I don't have this bug in "pipenv-2024.3.0"

**Comment by matteius** [comment]
pipdeptree vendowing was completed a few releases ago; I suspect these str conversions of the path are maybe involved but I don't know why it would be, so maybe something else 🤔 https://github.com/pypa/pipenv/pull/6300/files#diff-00868b196644e73191bf37befbde5a1aedb22dbc0b5920aa33eba63d6f119d66R112

**Comment by sanders41** [comment]
I did a bisect and 6f2929b is where the error started. Unfortunately it was a hacky bisect and I haven't been able to come up with a good minimal reproducer yet.

I'm not sure if it helps, but this lock file causes the error https://github.com/meilisearch/meilisearch-python/blob/9b2c99a9ad542907425bce946e60e6dba9be5edc/Pipfile.lock. I haven't yet come up with another lock file that reproduces it.

**Comment by sanders41** [comment]
I think I have figured out what the issue is, but I'm not sure the best way to go about fixing it. [Several paths](https://github.com/pypa/pipenv/blob/5a519796556af5957d125ebd29b2dfc36956882b/pipenv/vendor/pipdeptree/__main__.py#L9-L13) are added to `sys.path` in `pipdeptree/__main__.py` so that the imports can be found, but the command is run with [run_command](https://github.com/pypa/pipenv/blob/5a519796556af5957d125ebd29b2dfc36956882b/pipenv/utils/processes.py#L48) which uses a subprocess. Because it is run in a new process it doesn't have the appended paths.
