### ISSUE TITLE
Is it possible to use "proxy" setting available in pip

### ISSUE THREAD

**Issue by jeremy886** [pypa/pipenv#987]
I really like the ease of use of pipenv. But I'm still trying to find my way.

One thing I can't find in pip where I can set the proxy option:
--proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port

As I often need to work behind a firewall at my workplace (a school).

##### Describe you environment

1. Mac Sierra
1. Python version: Python 3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 23:01:38)
1. pipenv, version 8.2.5

##### Expected result

something like:
pipenv --proxy myproxy

Thanks.

**Comment by ivechan** [comment]
I think i would be a long time for pipenv to support it beause pip doesn't support proxy setting.
However, exporting the http_proxy environment variable can do the same thing(before running pipenv).
```
$ export http_proxy=your_server
$ export https_proxy=your_server
```

**Comment by erinxocon** [comment]
@ivechan pip does support installing from proxy if you pass it `--proxy`.  @nateprewitt @techalchemy Thoughts about adding a proxy section to the pipfile spec?

**Comment by techalchemy** [comment]
@erinxocon I feel like @kennethreitz wanted to keep as few things as possible in the Pipfile and kept pushing people to set up their pip.conf or pip.ini for things like this.  However, that would mean we will have to figure out how to respect those settings for pip-tools as well, and I am not sure how that would work.

**Comment by erinxocon** [comment]
@techalchemy That's what I was thinking.  We could use config files in the root of the project directory, but pip-tools doesn't currently respect that in our code.

**Comment by nateprewitt** [comment]
@erinxocon @techalchemy imo we need to respect pip.conf and the fact we aren't is a problem because we're rebuilding a lot of functionality pip should already handle (better) for us. We don't need the file to be in the directory, it's noted by a env variable or the default path established by pip. We just need to add a patch for pip-tools to respect it if it's not.

Also we definitely do not want a proxy entry in the Pipfile, that's user specific and isn't necessarily required. Anything that's system/instance specific should be left on the origin machine.

**Comment by kennethreitz** [comment]
not being supported, currently

**Comment by nitrocode** [comment]
@kennethreitz would you accept a pull request to support this? imho `npm` has the ideal method:

    npm config set https-proxy http://someproxy:8443

That way you can set it and forget it. Unlike pip where you need to use an alias to always add the proxy.

**Comment by fabiomolinar** [comment]
I would also be interested to hear more about this...

**Comment by singhgarima** [comment]
Any updates on this issue?

**Comment by TheFelixR** [comment]
I might as well bumb this again. Any updates? 

Right now I can put my proxy in ~/pip/pip.conf or ~/pip/pip.ini (linux or windows). But it would be much better if I just could add my proxy in the pipfile.

**Comment by orihomie** [comment]
Any updates? 🤔

**Comment by boukenka** [comment]
Is there any update? What is the current workaround?

**Comment by lijinglin2019** [comment]
Any updates?

**Comment by adamvm** [comment]
I will say something new: any updates ?

**Comment by TTimo** [comment]
Maybe re-open this?

**Comment by Tangogow** [comment]
Bumping. I'm stuck with 2 proxy between me and my Artifactory pypi repo.

Pip does work with `--extra-index-url` but pipenv with the same URL in the Pipefile doesn't.

**Comment by fridex** [comment]
> Bumping. I'm stuck with 2 proxy between me and my Artifactory pypi repo.
> 
> Pip does work with `--extra-index-url` but pipenv with the same URL in the Pipefile doesn't.

If you have a Pipfile.lock ready, you can try to use [micropipenv](https://github.com/thoth-station/micropipenv/#micropipenv-install):

```
micropipenv install -- --proxy myproxy
```

If the lock file is not present, micropipenv will not resolve it though.

**Comment by jankap** [comment]
`pip` does support proxy these days...
![image](https://user-images.githubusercontent.com/12893844/158196288-c033114d-1b5a-40ad-8ce5-2a847d32cd6c.png)
Please add a proxy option to `pipenv`, I can't rely on environmental variables.

**Comment by matteius** [comment]
I believe this is resolved now with my work on index restricted packages.  Correct me if I am wrong, but the proxy feature was specifically about using an alternate address (a proxy) on the internal network to bypass a firewall and connect to somewhere outside the network.  Since index restricted packages requires that all packages use a specific index, wouldn't it work to just specify the proxy address for that source in the Pipfile?

So for example:
```
[[source]]
url = " https://<usr_name>:<password>@<proxyserver_name>:<port#>"
verify_ssl = true
name = "my-proxy"

[packages]
requests = "*"

[dev-packages]

[requires]
python_version = "3.10"
```
